      Subroutine Type221

! Object: Sensible Air-to-Air Heat Recovery with Active Heat Exchanger
! Simulation Studio Model: Type221
! 

! Author: Vojtech Zavrel adopted from Jeff Thornton
! Editor: Vojtech Zavrel
! Date:	 November 07, 2021
! last modified: July 29, 2022
! 
! Air-to-Air Heat Recovery with Thermoelectric Heat Exchanger
! *** 
! *** Model Parameters 
! *** 
!			Humidity Mode	- [1;2]
!			Logical Unit for Performance Data	- [10;30]
!			Number of Points for Electric Current	- [1;+Inf]
!			Number of Points for Temperature Difference	- [1;+Inf]
!			Rated Electric Current	amperes [0.0;+Inf]
!			Rated Unit Flowrate	kg/hr [0.0;+Inf]
!			Number Thermoelectric Cells in Parallel	- [1;+Inf]
!			Number Thermoelectric Cells in Series	- [1;+Inf]
!			Thermal Loss Coeficient 	- [0;+Inf]
!			Electric Loss Coeficient	- [0;+Inf]

! *** 
! *** Model Inputs 
! *** 
!			Return Air Temperature	C [-Inf;+Inf]
!			Return Air Humidity Ratio	- [0.0;+Inf]
!			Return Air % Relative Humidity	- [0;100.]
!			Return Air Flowrate	kg/hr [0.0;+Inf]
!			Return Air Pressure	atm [0.;+Inf]
!			Return Air Pressure Drop	atm [0.0;+Inf]
!			Fresh Air Temperature	C [-Inf;+Inf]
!			Fresh Air Humidity Ratio	- [0.0;+Inf]
!			Fresh Air % Relative Humidity	- [0;100]
!			Fresh Air Flowrate	kg/hr [0.0;+Inf]
!			Fresh Air Pressure	atm [0.;+Inf]
!			Fresh Air Pressure Drop	atm [0.0;+Inf]
!			Sensible Effectiveness	Fraction [0;1.0]
!			On/Off Control Signal	- [0;1]
!			Electric current to Thermoelectric HX	amperes [0;+Inf]
!			Thermoelectric HX mode - cooling/heating	- [0;1]
!			Bypass signal - heat recovery HX	- [0;1]
!			Bypass signal - Thermoelectric HX	- [0;1]

! *** 
! *** Model Outputs 
! *** 
!			Exhaust Air Temperature	C [-Inf;+Inf]
!			Exhaust Air Humidity Ratio	- [0.0;+Inf]
!			Exhaust Air % Relative Humidity	- [0;100]
!			Exhaust Air Flowrate	kg/hr [0.0;+Inf]
!			Exhaust Air Pressure	atm [-Inf;+Inf]
!			Supply Air Temperature	C [-Inf;+Inf]
!			Supply Air Humidity Ratio	- [0.0;+Inf]
!			Supply Air % Relative Humidity	- [0.0;100.0]
!			Supply Air Flowrate 	kg/hr [0.0;+Inf]
!			Supply Air Pressure	atm [-Inf;+Inf]
!			Heat Transfer Rate - Heat recovery	kJ/hr [-Inf;+Inf]
!			Heat Transfer Rate to Supply Air - Thermoelectric HX 	- [-Inf;+Inf]
!			Heat Transfer Rate to Exhaust Air - Thermoelectric HX	- [-Inf;+Inf]
!			Power - Thermoelectric HX	kJ/hr [-Inf;+Inf]
!			COP - Thermoelectric HX	- [-Inf;+Inf]
!			EER - Thermoelectric HX	- [-Inf;+Inf]
!			Condensate Temperature - Exhaust Stream	C [-Inf;+Inf]
!			Condensate Flowrate - Exhaust Stream	kg/hr [-Inf;+Inf]
!			Condensate Temperature - Supply Air Stream	C [-Inf;+Inf]
!			Condensate Flowrate - Supply Air Stream	kg/hr [-Inf;+Inf]
!			Heat Recovery Outlet Temperature	C [-Inf;+Inf]
!			Heat Recovery Outlet Humidity Ratio	- [0.0;+Inf]
!			Heat Recovery Outlet % Relative Humidity	- [0.0;100.0]

! *** 
! *** Model Derivatives 
! *** 

! (Comments and routine interface generated by TRNSYS Simulation Studio)
!************************************************************************

!-----------------------------------------------------------------------------------------------------------------------
! This TRNSYS component skeleton was generated from the TRNSYS studio based on the user-supplied parameters, inputs, 
! outputs, and derivatives.  The user should check the component formulation carefully and add the content to transform
! the parameters, inputs and derivatives into outputs.  Remember, outputs should be the average value over the timestep
! and not the value at the end of the timestep; although in many models these are exactly the same values.  Refer to 
! existing types for examples of using advanced features inside the model (Formats, Labels etc.)
!-----------------------------------------------------------------------------------------------------------------------


      Use TrnsysConstants
      Use TrnsysFunctions

!-----------------------------------------------------------------------------------------------------------------------

!DEC$Attributes DLLexport :: Type221

!-----------------------------------------------------------------------------------------------------------------------
!Trnsys Declarations
      Implicit None

      Double Precision Timestep,Time
      Integer CurrentUnit,CurrentType



	
	 
!    PARAMETERS
             
      
      INTEGER Humidity_Mode
      INTEGER Logical_Unit_for_Performance_Data
      DOUBLE PRECISION Number_of_Points_for_Electric_Current
      DOUBLE PRECISION Number_of_Points_for_Temperature_Difference
      DOUBLE PRECISION Rated_Electric_Current
      DOUBLE PRECISION Rated_Unit_Flowrate
      DOUBLE PRECISION Number_Thermoelectric_Cells_in_Parallel
      DOUBLE PRECISION Number_Thermoelectric_Cells_in_Series
      DOUBLE PRECISION Thermal_Loss_Coeficient
      DOUBLE PRECISION Electric_Loss_Coeficient

!    INPUTS
      DOUBLE PRECISION Return_Air_Temperature
      DOUBLE PRECISION Return_Air_Humidity_Ratio
      DOUBLE PRECISION Return_Air_Relative_Humidity
      DOUBLE PRECISION Return_Air_Flowrate
      DOUBLE PRECISION Return_Air_Pressure
      DOUBLE PRECISION Return_Air_Pressure_Drop
      DOUBLE PRECISION Fresh_Air_Temperature
      DOUBLE PRECISION Fresh_Air_Humidity_Ratio
      DOUBLE PRECISION Fresh_Air_Relative_Humidity
      DOUBLE PRECISION Fresh_Air_Flowrate
      DOUBLE PRECISION Fresh_Air_Pressure
      DOUBLE PRECISION Fresh_Air_Pressure_Drop
      DOUBLE PRECISION Sensible_Effectiveness
      DOUBLE PRECISION On_Off_Control_Signal
      DOUBLE PRECISION Electric_current_to_Thermoelectric_HX
      DOUBLE PRECISION Thermoelectric_HX_mode_cooling_heating
      DOUBLE PRECISION Bypass_signal_heat_recovery_HX
      DOUBLE PRECISION Bypass_signal_Thermoelectric_HX
	  
!    OUTPUTS 
      DOUBLE PRECISION  Exhaust_Air_Temperature
	  DOUBLE PRECISION  Exhaust_Air_Humidity_Ratio
	  DOUBLE PRECISION  Exhaust_Air_Relative_Humidity
	  DOUBLE PRECISION  Exhaust_Air_Flowrate
	  DOUBLE PRECISION  Exhaust_Air_Pressure
	  DOUBLE PRECISION  Supply_Air_Temperature
	  DOUBLE PRECISION  Supply_Air_Humidity_Ratio
	  DOUBLE PRECISION  Supply_Air_Relative_Humidity
	  DOUBLE PRECISION  Supply_Air_Flowrate
	  DOUBLE PRECISION  Supply_Air_Pressure
	  DOUBLE PRECISION  Heat_Transfer_Rate_HR
	  DOUBLE PRECISION  Heat_Transfer_Rate_aHX_sup
	  DOUBLE PRECISION  Heat_Transfer_Rate_aHX_exh
	  DOUBLE PRECISION  Power_aHX
	  DOUBLE PRECISION  COP_aHX
	  DOUBLE PRECISION  EER_aHX
	  DOUBLE PRECISION  Condensate_Temperature_Exh
	  DOUBLE PRECISION  Condensate_Flowrate_Exh	  
	  DOUBLE PRECISION  Condensate_Temperature_Sup
	  DOUBLE PRECISION  Condensate_Flowrate_Sup
	  DOUBLE PRECISION	Heat_Recovery_Outlet_Temperature
	  DOUBLE PRECISION	Heat_Recovery_Outlet_Humidity_Ratio
	  DOUBLE PRECISION	Heat_Recovery_Outlet_Relative_Humidity	  
	  
!	AUXILIARY
	  DOUBLE PRECISION T_K,P_kPa,cP_exh, Cap_exh,cp_pas_sup,Cap_pas_sup,X(2),Y(2)
	  INTEGER psychmode,status, nIND,nX(2),nY, i
	  DOUBLE PRECISION Return_Air_Enthalpy,Exhaust_Air_Enthalpy,Fresh_Air_Enthalpy,Supply_Air_Enthalpy, Tdw_pas_exh, Tdw_pas_sup,H_pas_exh,p_pas_exh,w_pas_exh,t_pas_exh,p_pas_sup,t_pas_sup,w_pas_sup,H_pas_sup,Cond_Pas_Sup, Cond_Pas_Exh
	  DOUBLE PRECISION airprops(5),psydat(9)
	  DOUBLE PRECISION Qc_cell(20),Qh_cell(20),U_cell(20),I_cell,P_cell(20), dT_cell(20),H_c_cell(20),H_h_cell(20), w_c_cell(20),w_h_cell(20),T_c_cell(20),T_h_cell(20),M_c_cell, M_h_cell, p_c_cell, p_h_cell
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Get the Global Trnsys Simulation Variables
      Time=getSimulationTime()
      Timestep=getSimulationTimeStep()
      CurrentUnit = getCurrentUnit()
      CurrentType = getCurrentType()
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Set the Version Number for This Type
      If(getIsVersionSigningTime()) Then
		Call SetTypeVersion(17)
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do Any Last Call Manipulations Here
      If(getIsLastCallofSimulation()) Then
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Perform Any "After Convergence" Manipulations That May Be Required at the End of Each Timestep
      If(getIsEndOfTimestep()) Then
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do All of the "Very First Call of the Simulation Manipulations" Here
      If(getIsFirstCallofSimulation()) Then

		!Tell the TRNSYS Engine How This Type Works
		Call SetNumberofParameters(10)           !The number of parameters that the the model wants
		Call SetNumberofInputs(18)                   !The number of inputs that the the model wants
		Call SetNumberofDerivatives(0)         !The number of derivatives that the the model wants
		Call SetNumberofOutputs(23)                 !The number of outputs that the the model produces
		Call SetIterationMode(1)                             !An indicator for the iteration mode (default=1).  Refer to section 8.4.3.5 of the documentation for more details.
		Call SetNumberStoredVariables(0,0)                   !The number of static variables that the model wants stored in the global storage array and the number of dynamic variables that the model wants stored in the global storage array
		Call SetNumberofDiscreteControls(0)               !The number of discrete control functions set by this model (a value greater than zero requires the user to use Solver 1: Powell's method)

		Call SetInputUnits(1,'TE1')    
		Call SetInputUnits(2,'DM1')    
		Call SetInputUnits(3,'PC1')    
		Call SetInputUnits(4,'MF1')    
		Call SetInputUnits(5,'PR4')    
		Call SetInputUnits(6,'PR4')    
		Call SetInputUnits(7,'TE1')    
		Call SetInputUnits(8,'DM1')    
		Call SetInputUnits(9,'PC1')    
		Call SetInputUnits(10,'MF1')    
		Call SetInputUnits(11,'PR4')    
		Call SetInputUnits(12,'PR4')    
		Call SetInputUnits(13,'DM1')    
		Call SetInputUnits(14,'CF1')    
		Call SetInputUnits(15,'CU1') 
		Call SetInputUnits(16,'CF1') 
		Call SetInputUnits(17,'CF1') 
		Call SetInputUnits(18,'CF1') 			

		Call SetOutputUnits(1,'TE1')    
		Call SetOutputUnits(2,'DM1')    
		Call SetOutputUnits(3,'PC1')    
		Call SetOutputUnits(4,'MF1')    
		Call SetOutputUnits(5,'PR4')    
		Call SetOutputUnits(6,'TE1')    
		Call SetOutputUnits(7,'DM1')    
		Call SetOutputUnits(8,'PC1')    
		Call SetOutputUnits(9,'MF1')    
		Call SetOutputUnits(10,'PR4')    
		Call SetOutputUnits(11,'PW1')    
		Call SetOutputUnits(12,'PW1') 
		Call SetOutputUnits(13,'PW1') 	
		Call SetOutputUnits(14,'PW1') 		
		Call SetOutputUnits(15,'DM1') 
		Call SetOutputUnits(16,'DM1') 		
		Call SetOutputUnits(17,'TE1')    
		Call SetOutputUnits(18,'MF1')    
		Call SetOutputUnits(19,'TE1')    
		Call SetOutputUnits(20,'MF1')  
        Call SetOutputUnits(21,'TE1')    
		Call SetOutputUnits(22,'DM1')    
		Call SetOutputUnits(23,'PC1')    



		Return

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do All of the First Timestep Manipulations Here - There Are No Iterations at the Intial Time
      If (getIsStartTime()) Then
      Humidity_Mode = JFIX(getParameterValue(1)+0.1)
      Logical_Unit_for_Performance_Data = JFIX(getParameterValue(2)+0.1)
      Number_of_Points_for_Electric_Current = JFIX(getParameterValue(3)+0.1)
      Number_of_Points_for_Temperature_Difference = JFIX(getParameterValue(4)+0.1)
      Rated_Electric_Current = JFIX(getParameterValue(5)+0.1)
      Rated_Unit_Flowrate = JFIX(getParameterValue(6)+0.1)
	  Number_Thermoelectric_Cells_in_Parallel = JFIX(getParameterValue(7)+0.1)
      Number_Thermoelectric_Cells_in_Series = JFIX(getParameterValue(8)+0.1)
      Thermal_Loss_Coeficient = JFIX(getParameterValue(9)+0.1)
      Electric_Loss_Coeficient = JFIX(getParameterValue(10)+0.1)


      Return_Air_Temperature = GetInputValue(1)
      Return_Air_Humidity_Ratio = GetInputValue(2)
      Return_Air_Relative_Humidity = GetInputValue(3)
      Return_Air_Flowrate = GetInputValue(4)
      Return_Air_Pressure = GetInputValue(5)
      Return_Air_Pressure_Drop = GetInputValue(6)
      Fresh_Air_Temperature = GetInputValue(7)
      Fresh_Air_Humidity_Ratio = GetInputValue(8)
      Fresh_Air_Relative_Humidity = GetInputValue(9)
      Fresh_Air_Flowrate = GetInputValue(10)
      Fresh_Air_Pressure = GetInputValue(11)
      Fresh_Air_Pressure_Drop = GetInputValue(12)
      Sensible_Effectiveness = GetInputValue(13)
      On_Off_Control_Signal = GetInputValue(14)
      Electric_current_to_Thermoelectric_HX = GetInputValue(15)
      Thermoelectric_HX_mode_cooling_heating = GetInputValue(16)
      Bypass_signal_heat_recovery_HX = GetInputValue(17)
      Bypass_signal_Thermoelectric_HX = GetInputValue(18)

	
   !Check the Parameters for Problems (#,ErrorType,Text)
   !Sample Code: If( PAR1 <= 0.) Call FoundBadParameter(1,'Fatal','The first parameter provided to this model is not acceptable.')
     If ((Humidity_Mode < 1) .or. (Humidity_Mode > 2)) Call FoundBadParameter(1,'Fatal','The humidity mode must be 1 or 2.')
     If (Logical_Unit_for_Performance_Data < 10) Call FoundBadParameter(2,'fatal','The data file logical unit number must be greater than 10.')
     If (Number_of_Points_for_Electric_Current < 2) Call FoundBadParameter(3,'fatal','There must be 2 or more datapoints for electric current in the data file.')   
     If (Number_of_Points_for_Temperature_Difference < 2) Call FoundBadParameter(4,'fatal','There must be 2 or more datapoints for temperature difference in the data file.')   
     If (Rated_Electric_Current < 0.d0) Call FoundBadParameter(5,'fatal','The parameter "Rated Electric Current" must be positive.')
     If (Rated_Unit_Flowrate < 0.d0) Call FoundBadParameter(6,'fatal','The parameter "Rated Electric Current" must be positive.')
     If (Number_Thermoelectric_Cells_in_Parallel <= 0.d0) Call FoundBadParameter(7,'fatal','The parameter "Number Thermoelectric Cells in Parallel" must be positive.')
     If (Number_Thermoelectric_Cells_in_Series <= 0.d0) Call FoundBadParameter(8,'fatal','The parameter "Number Thermoelectric Cells in Series" must be positive.')
     If (Thermal_Loss_Coeficient  < 0.d0) Call FoundBadParameter(9,'fatal','The parameter "Thermal Loss Coeficient " must be positive.')
     If (Electric_Loss_Coeficient  < 0.d0) Call FoundBadParameter(10,'fatal','The parameter "Electric Loss Coeficient " must be positive.')
   
   
   
   !Set the Initial Values of the Outputs (#,Value)
		Call SetOutputValue(1, 20.0) ! Exhaust Air Temperature
		Call SetOutputValue(2, 0.001) ! Exhaust Air Humidity Ratio
		Call SetOutputValue(3, 50.0) ! Exhaust Air % Relative Humidity
		Call SetOutputValue(4, 0.d0) ! Exhaust Air Flowrate
		Call SetOutputValue(5, 0.d0) ! Exhaust Air Pressure
		Call SetOutputValue(6, 20.0) ! Supply Air Temperature
		Call SetOutputValue(7, 0.001) ! Supply Air Humidity Ratio
		Call SetOutputValue(8, 50.0) ! Supply Air % Relative Humidity
		Call SetOutputValue(9, 0.0) ! Supply Air Flowrate 
		Call SetOutputValue(10, 0.d0) ! Supply Air Pressure
		Call SetOutputValue(11, 0.0) ! Heat Transfer Rate - Heat recovery
		Call SetOutputValue(12, 0.d0) ! Heat Transfer Rate to Supply Air - Thermoelectric HX 
		Call SetOutputValue(13, 0.d0) ! Heat Transfer Rate to Exhaust Air - Thermoelectric HX
		Call SetOutputValue(14, 0.0) ! Power - Thermoelectric HX
		Call SetOutputValue(15, 0.d0) ! COP - Thermoelectric HX
		Call SetOutputValue(16, 0.d0) ! EER - Thermoelectric HX
		Call SetOutputValue(17, 0.d0) ! Condensate Temperature - Exhaust Stream
		Call SetOutputValue(18, 0.d0) ! Condensate Flowrate - Exhaust Stream
		Call SetOutputValue(19, 0.d0) ! Condensate Temperature - Supply Air Stream
		Call SetOutputValue(20, 0.d0) ! Condensate Flowrate - Supply Air Stream
		Call SetOutputValue(21, 0.d0) !	Heat Recovery Outlet Temperature	C [-Inf;+Inf]
		Call SetOutputValue(22, 0.d0) ! Heat Recovery Outlet Humidity Ratio	- [0.0;+Inf]
		Call SetOutputValue(23, 0.d0) ! Heat Recovery Outlet % Relative Humidity	- [0.0;100.0]
		
		



   !If Needed, Set the Initial Values of the Static Storage Variables (#,Value)
   !Sample Code: SetStaticArrayValue(1,0.d0)

   !If Needed, Set the Initial Values of the Dynamic Storage Variables (#,Value)
   !Sample Code: Call SetDynamicArrayValueThisIteration(1,20.d0)

   !If Needed, Set the Initial Values of the Discrete Controllers (#,Value)
   !Sample Code for Controller 1 Set to Off: Call SetDesiredDiscreteControlState(1,0) 

		Return

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!ReRead the Parameters if Another Unit of This Type Has Been Called Last
      If(getIsReReadParameters()) Then
		!Read in the Values of the Parameters from the Input File
      Humidity_Mode = getParameterValue(1)
      Logical_Unit_for_Performance_Data = getParameterValue(2)
      Number_of_Points_for_Electric_Current = getParameterValue(3)
      Number_of_Points_for_Temperature_Difference = getParameterValue(4)
      Rated_Electric_Current = getParameterValue(5)
	  Rated_Unit_Flowrate = getParameterValue(6)
      Number_Thermoelectric_Cells_in_Parallel = getParameterValue(7)
      Number_Thermoelectric_Cells_in_Series = getParameterValue(8)
      Thermal_Loss_Coeficient = getParameterValue(9)
      Electric_Loss_Coeficient = getParameterValue(10)

		
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!Read the Inputs
      Return_Air_Temperature = GetInputValue(1)
      Return_Air_Humidity_Ratio = GetInputValue(2)
      Return_Air_Relative_Humidity = GetInputValue(3)
      Return_Air_Flowrate = GetInputValue(4)
      Return_Air_Pressure = GetInputValue(5)
      Return_Air_Pressure_Drop = GetInputValue(6)
      Fresh_Air_Temperature = GetInputValue(7)
      Fresh_Air_Humidity_Ratio = GetInputValue(8)
      Fresh_Air_Relative_Humidity = GetInputValue(9)
      Fresh_Air_Flowrate = GetInputValue(10)
      Fresh_Air_Pressure = GetInputValue(11)
      Fresh_Air_Pressure_Drop = GetInputValue(12)
      Sensible_Effectiveness = GetInputValue(13)
      On_Off_Control_Signal = GetInputValue(14)
      Electric_current_to_Thermoelectric_HX = GetInputValue(15)
      Thermoelectric_HX_mode_cooling_heating = GetInputValue(16)
      Bypass_signal_heat_recovery_HX = GetInputValue(17)
      Bypass_signal_Thermoelectric_HX = GetInputValue(18)
		

		If (Electric_current_to_Thermoelectric_HX>Rated_Electric_Current*1.2) Call FoundBadInput(15,'warning','The input #15 "Electric Current to Thermoelectric HX" exceeded the parameter #5 "Rated Electric Current" about more than 20% in this step. The input #15 "Electric Current to Thermoelectric HX" was set 0.0 to simulate the inner emergency logic preventing overloading. If these warnings occur repetitively, check settings of parameters #5 "Rated Electric Current", adjust the external control function or increase the limit # of Warnings Before Error in Advanced Settings.')
		If (Electric_current_to_Thermoelectric_HX>Rated_Electric_Current*1.2) Then
		Electric_current_to_Thermoelectric_HX=0.0
		Endif
	!Check the Inputs for Problems (#,ErrorType,Text)
	!Sample Code: If( IN1 <= 0.) Call FoundBadInput(1,'Fatal','The first input provided to this model is not acceptable.')
    ! don't forget to add!
      If(ErrorFound()) Return
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!    *** PERFORM ALL THE CALCULATION HERE FOR THIS MODEL. ***
!-----------------------------------------------------------------------------------------------------------------------

! Set the correct inlet state
 If (Humidity_Mode	 == 1) Then
    psychmode = 4
 Else
    psychmode = 2
 EndIf

! Set the return air - inlet properties
 psydat(1) = Return_Air_Pressure
 psydat(2) = Return_Air_Temperature
 psydat(4) = Return_Air_Relative_Humidity
 psydat(6) = Return_Air_Humidity_Ratio
 Call MoistAirProperties(CurrentUnit,CurrentType,1,psychmode,0,psydat,1,status)
 If (ErrorFound()) Return
 Return_Air_Temperature= psydat(2)
 Return_Air_Relative_Humidity = psydat(4)
 Return_Air_Humidity_Ratio = psydat(6)
 Return_Air_Enthalpy	 = psydat(7)
 


! Set the fresh air - inlet properties
 psydat(1) = Fresh_Air_Pressure
 psydat(2) = Fresh_Air_Temperature
 psydat(4) = Fresh_Air_Relative_Humidity
 psydat(6) = Fresh_Air_Humidity_Ratio
 Call MoistAirProperties(CurrentUnit,CurrentType,1,psychmode,0,psydat,1,status)
 If (ErrorFound()) Return
 Fresh_Air_Temperature = psydat(2)
 Fresh_Air_Relative_Humidity = psydat(4)
 Fresh_Air_Humidity_Ratio = psydat(6)
 Fresh_Air_Enthalpy = psydat(7)
 



!**************************************************************
! Set the off-conditions results
!**************************************************************
 If ((On_Off_Control_Signal <= 0.) .or. (Fresh_Air_Flowrate <= 0.10*Rated_Unit_Flowrate) .or. (Return_Air_Flowrate <= 0.10*Rated_Unit_Flowrate)) Then
	If (Fresh_Air_Flowrate > 0.0 .and. Fresh_Air_Flowrate<= 0.10*Rated_Unit_Flowrate) Call FoundBadInput(10,'warning','The input #10 "Fresh Air Flowrate" is below 10% of parameter #6 Rated unit flowrate but not 0. The type was set into off state for this timestep to simulate the pressure drop effect of the device. 10% of rated flow rate is considered as minimum possible flowrate for operation. If these warnings occur repetitively, check settings of parameters #6 " Rated unit flowrate ", adjust the external control function or increase the limit # of Warnings Before Error in Advanced Settings.')	
	If (Return_Air_Flowrate > 0.0 .and. Return_Air_Flowrate<= 0.10*Rated_Unit_Flowrate) Call FoundBadInput(4,'warning','The input #4 "Return Air Flowrate" is below 10% of parameter #6 Rated unit flowrate but not 0. The type was set into off state for this timestep to simulate the pressure drop effect of the device. 10% of rated flow rate is considered as minimum possible flowrate for operation. If these warnings occur repetitively, check settings of parameters #6 " Rated unit flowrate ", adjust the external control function or increase the limit # of Warnings Before Error in Advanced Settings.')	
 
 ! Set the exhaust air - outlet properties
    Exhaust_Air_Pressure = Return_Air_Pressure - Return_Air_Pressure_Drop
    Exhaust_Air_Enthalpy = Return_Air_Enthalpy	
    Exhaust_Air_Humidity_Ratio = Return_Air_Humidity_Ratio
  
		
    psydat(1) = Exhaust_Air_Pressure
    psydat(6) = Exhaust_Air_Humidity_Ratio
    psydat(7) = Exhaust_Air_Enthalpy
	
    Call MoistAirProperties(CurrentUnit,CurrentType,1,7,0,psydat,1,status)
    If (ErrorFound()) Return


	Exhaust_Air_Enthalpy = psydat(7)
 
    Exhaust_Air_Temperature = psydat(2)
    Exhaust_Air_Relative_Humidity = psydat(4)
    Exhaust_Air_Humidity_Ratio = psydat(6)
    Exhaust_Air_Flowrate = Return_Air_Flowrate
    Exhaust_Air_Pressure = psydat(1)
    Tdw_pas_exh=psydat(5)
  
  
    ! Set the supply air - outlet properties
    Supply_Air_Pressure = Fresh_Air_Pressure-Fresh_Air_Pressure_Drop
    Supply_Air_Enthalpy = Fresh_Air_Enthalpy
    Supply_Air_Humidity_Ratio = Fresh_Air_Humidity_Ratio

    psydat(1) = Supply_Air_Pressure
    psydat(6) = Supply_Air_Humidity_Ratio
    psydat(7) = Supply_Air_Enthalpy
	
    Call MoistAirProperties(CurrentUnit,CurrentType,1,7,0,psydat,1,status)
    If (ErrorFound()) Return
    
	Supply_Air_Enthalpy = psydat(7)
	

    Supply_Air_Temperature = psydat(2)
    Supply_Air_Relative_Humidity = psydat(4)
    Supply_Air_Humidity_Ratio = psydat(6)
	Supply_Air_Flowrate = Fresh_Air_Flowrate
    Supply_Air_Pressure = psydat(1)
	Tdw_pas_sup=psydat(5)
    !Set the outlet heat recovery air properties
	Heat_Recovery_Outlet_Temperature=psydat(2)
	Heat_Recovery_Outlet_Humidity_Ratio=psydat(6)
	Heat_Recovery_Outlet_Relative_Humidity=psydat(4)



    Heat_Transfer_Rate_HR = 0.
	Heat_Transfer_Rate_aHX_exh = 0.
	Heat_Transfer_Rate_aHX_sup = 0.
    Power_aHX = 0.
	COP_aHX = 0.
	EER_aHX = 0.




! Set the condensate conditions
    Condensate_Temperature_Sup = Tdw_pas_sup
    Condensate_Flowrate_Sup	 = DMAX1(0.,(Fresh_Air_Flowrate*(Fresh_Air_Humidity_Ratio-Supply_Air_Humidity_Ratio)))

    Condensate_Temperature_Exh = Tdw_pas_exh
    Condensate_Flowrate_Exh	 = DMAX1(0.,(Return_Air_Flowrate*(Return_Air_Humidity_Ratio-Exhaust_Air_Humidity_Ratio)))


 Else
 !**************************************************************
 ! Set the outlets with no heat transfer -> full bypass
 !**************************************************************
	
	If ((Bypass_signal_heat_recovery_HX>= 0.5) .and. ((Bypass_signal_Thermoelectric_HX >= 0.5) .or. (Electric_current_to_Thermoelectric_HX <= 0.))) Then 
		! Set the outlets with no heat transfer
		
		! Set the exhaust air - outlet properties
    Exhaust_Air_Pressure = Return_Air_Pressure-Return_Air_Pressure_Drop
    Exhaust_Air_Enthalpy = Return_Air_Enthalpy	
    Exhaust_Air_Humidity_Ratio = Return_Air_Humidity_Ratio
  
		
    psydat(1) = Exhaust_Air_Pressure
    psydat(6) = Exhaust_Air_Humidity_Ratio
    psydat(7) = Exhaust_Air_Enthalpy
	
    Call MoistAirProperties(CurrentUnit,CurrentType,1,7,0,psydat,1,status)
    If (ErrorFound()) Return


	Exhaust_Air_Enthalpy = psydat(7)

    Exhaust_Air_Temperature = psydat(2)
    Exhaust_Air_Relative_Humidity = psydat(4)
    Exhaust_Air_Humidity_Ratio = psydat(6)
    Exhaust_Air_Flowrate = Return_Air_Flowrate
    Exhaust_Air_Pressure = psydat(1)
	Tdw_pas_exh=psydat(5)

  
  
    ! Set the supply air - outlet properties
    Supply_Air_Pressure = Fresh_Air_Pressure-Fresh_Air_Pressure_Drop
    Supply_Air_Enthalpy = Fresh_Air_Enthalpy
    Supply_Air_Humidity_Ratio = Fresh_Air_Humidity_Ratio

    psydat(1) = Supply_Air_Pressure
    psydat(6) = Supply_Air_Humidity_Ratio
    psydat(7) = Supply_Air_Enthalpy
	
    Call MoistAirProperties(CurrentUnit,CurrentType,1,7,0,psydat,1,status)
    If (ErrorFound()) Return
    
	Supply_Air_Enthalpy = psydat(7)
    Supply_Air_Temperature = psydat(2)
    Supply_Air_Relative_Humidity = psydat(4)
    Supply_Air_Humidity_Ratio = psydat(6)
	Supply_Air_Flowrate = Fresh_Air_Flowrate
    Supply_Air_Pressure = psydat(1)
	Tdw_pas_sup=psydat(5)
    !Set the outlet heat recovery air properties
	Heat_Recovery_Outlet_Temperature=psydat(2)
	Heat_Recovery_Outlet_Humidity_Ratio=psydat(6)
	Heat_Recovery_Outlet_Relative_Humidity=psydat(4)



    Heat_Transfer_Rate_HR = 0.
	Heat_Transfer_Rate_aHX_exh = 0.
	Heat_Transfer_Rate_aHX_sup = 0.
    Power_aHX = 0.
	!to add warning if I >0, the cell would overheat
	COP_aHX = 0.
	EER_aHX = 0.




! Set the condensate conditions
    Condensate_Temperature_Sup = Tdw_pas_sup
    Condensate_Flowrate_Sup	 = DMAX1(0.,(Fresh_Air_Flowrate*(Fresh_Air_Humidity_Ratio-Supply_Air_Humidity_Ratio)))

    Condensate_Temperature_Exh = Tdw_pas_exh
    Condensate_Flowrate_Exh	 = DMAX1(0.,(Return_Air_Flowrate*(Return_Air_Humidity_Ratio-Exhaust_Air_Humidity_Ratio)))


	
!**********************************************************************************
! Only passive HX is on, the active HX is bypassed or off
!**********************************************************************************
	Elseif ((Bypass_signal_heat_recovery_HX< 0.5) .and. ((Bypass_signal_Thermoelectric_HX >= 0.5) .or. (Electric_current_to_Thermoelectric_HX <= 0.))) Then
				! Set the outlets with no heat transfer
		
		
! ------ Calculate the sensible heat transfer based on the effectiveness approach------	
       ! Air stream capacity calculation
        T_K = Return_Air_Temperature+273.15
		P_kPa = Return_Air_Pressure*101.325
		Call AirProp(T_K,P_kPa,airprops)
		cP_exh = airprops(5)
		Cap_exh = cP_exh*Return_Air_Flowrate	
	   


		T_K = Fresh_Air_Temperature+273.15	
		P_kPa = Fresh_Air_Pressure*101.325
		Call AirProp(T_K,P_kPa,airprops)
		cp_pas_sup = airprops(5)
		Cap_pas_sup = cp_pas_sup*Fresh_Air_Flowrate

		Heat_Transfer_Rate_HR = Sensible_Effectiveness*DMIN1(Cap_exh,Cap_pas_sup)*(Return_Air_Temperature-Fresh_Air_Temperature)
!----------------------------------------------------------------------------------------

        !energy and humidity ratio balance
		Exhaust_Air_Enthalpy = Return_Air_Enthalpy	- Heat_Transfer_Rate_HR/Return_Air_Flowrate 	! Calculate the enthalpy of the exhaust air stream from an energy balance
	    Exhaust_Air_Pressure = Return_Air_Pressure - Return_Air_Pressure_Drop
		Exhaust_Air_Humidity_Ratio = Return_Air_Humidity_Ratio !No humidity recovery is considered

		
        Supply_Air_Enthalpy = Fresh_Air_Enthalpy+Heat_Transfer_Rate_HR/Fresh_Air_Flowrate ! Calculate the enthalpy of the fresh air stream from an energy balance
        Supply_Air_Pressure = Fresh_Air_Pressure-Fresh_Air_Pressure_Drop
		Supply_Air_Humidity_Ratio = Fresh_Air_Humidity_Ratio 		
		

	    ! Calculate the outlet states
			psydat(1) = Exhaust_Air_Pressure
			psydat(6) = Exhaust_Air_Humidity_Ratio
			psydat(7) = Exhaust_Air_Enthalpy
			Call MoistAirProperties(CurrentUnit,CurrentType,1,7,0,psydat,1,status)
			If (ErrorFound()) Return
		Exhaust_Air_Pressure = psydat(1)
		Exhaust_Air_Temperature = psydat(2)
		Exhaust_Air_Relative_Humidity = psydat(4)
		Exhaust_Air_Humidity_Ratio = psydat(6)
		Exhaust_Air_Enthalpy = psydat(7)
		Tdw_pas_exh=psydat(5)

			psydat(1) = Supply_Air_Pressure
			psydat(6) = Supply_Air_Humidity_Ratio
			psydat(7) = Supply_Air_Enthalpy
			Call MoistAirProperties(CurrentUnit,CurrentType,1,7,0,psydat,1,status)
			If (ErrorFound()) Return
		Supply_Air_Pressure = psydat(1)
		Supply_Air_Temperature = psydat(2)
		Supply_Air_Relative_Humidity = psydat(4)
		Supply_Air_Humidity_Ratio = psydat(6)
		Supply_Air_Enthalpy = psydat(7)
		Tdw_pas_sup=psydat(5)
		
		        !Set the outlet heat recovery air properties
		 Heat_Recovery_Outlet_Temperature=psydat(2)
		 Heat_Recovery_Outlet_Humidity_Ratio=psydat(6)
		 Heat_Recovery_Outlet_Relative_Humidity=psydat(4)
		
		Heat_Transfer_Rate_aHX_exh = 0.
	    Heat_Transfer_Rate_aHX_sup = 0.
        Power_aHX = 0.
	    COP_aHX = 0.
	    EER_aHX = 0.
	
	    ! Set the condensate conditions
        Condensate_Temperature_Sup = Tdw_pas_sup
        Condensate_Flowrate_Sup	 = DMAX1(0.,(Fresh_Air_Flowrate*(Fresh_Air_Humidity_Ratio-Supply_Air_Humidity_Ratio)))

        Condensate_Temperature_Exh = Tdw_pas_exh
        Condensate_Flowrate_Exh	 = DMAX1(0.,(Return_Air_Flowrate*(Return_Air_Humidity_Ratio-Exhaust_Air_Humidity_Ratio)))

	
!**************************************************************
   ! passive HX is bypassed, only the active HX is on
!**************************************************************
	Elseif ((Bypass_signal_heat_recovery_HX>= 0.5) .and. ((Bypass_signal_Thermoelectric_HX < 0.5) .and. (Electric_current_to_Thermoelectric_HX > 0.))) Then
! ----------- ---Active HX inicialization ----------------------	
		!initial conditions
		        !Set the outlet heat recovery air properties
		 Heat_Recovery_Outlet_Temperature=Fresh_Air_Temperature
		 Heat_Recovery_Outlet_Humidity_Ratio=Fresh_Air_Humidity_Ratio
		 Heat_Recovery_Outlet_Relative_Humidity=Fresh_Air_Relative_Humidity		
		
	
		
		If (Thermoelectric_HX_mode_cooling_heating<0.5) Then !cooling mode = 0 
			M_c_cell=Fresh_Air_Flowrate/Number_Thermoelectric_Cells_in_Parallel ! massflow over series of cell - even distribution assumption
			p_c_cell= Fresh_Air_Pressure-Fresh_Air_Pressure_Drop		
			H_c_cell(1)=Fresh_Air_Enthalpy
			w_c_cell(1)=Fresh_Air_Humidity_Ratio
			T_c_cell(1)=Fresh_Air_Temperature
			
			
			M_h_cell=Return_Air_Flowrate/Number_Thermoelectric_Cells_in_Parallel ! massflow over series of cell - even distribution assumption
			p_h_cell= Return_Air_Pressure - Return_Air_Pressure_Drop
			H_h_cell(1)=Return_Air_Enthalpy
			w_h_cell(1)=Return_Air_Humidity_Ratio
			T_h_cell(1)=Return_Air_Temperature
			!dT_cell(1)=DMAX1(0.0,Fresh_Air_Temperature-Return_Air_Temperature)
		
		Else ! heating mode = 1
		
			M_c_cell=Return_Air_Flowrate/Number_Thermoelectric_Cells_in_Parallel ! massflow over series of cell - even distribution assumption
			p_c_cell= Return_Air_Pressure - Return_Air_Pressure_Drop
			H_c_cell(1)=Return_Air_Enthalpy
			w_c_cell(1)=Return_Air_Humidity_Ratio
			T_c_cell(1)=Return_Air_Temperature
			
			
			M_h_cell=Fresh_Air_Flowrate/Number_Thermoelectric_Cells_in_Parallel ! massflow over series of cell - even distribution assumption
			p_h_cell= Fresh_Air_Pressure-Fresh_Air_Pressure_Drop
			H_h_cell(1)=Fresh_Air_Enthalpy
			w_h_cell(1)=Fresh_Air_Humidity_Ratio
			T_h_cell(1)=Fresh_Air_Temperature
			!dT_cell(1)=DMAX1(0.0,Return_Air_Temperature-Fresh_Air_Temperature)
		
		Endif
		
		dT_cell(1)=abs(Return_Air_Temperature-Fresh_Air_Temperature)
		I_cell=Electric_current_to_Thermoelectric_HX
		U_cell(1)=0.0
		P_cell(1)=0.0
		
		Qc_cell(1)=0.0
		Qh_cell(1)=0.0
		
! --------------Active HX calculation-----------------------
		! interpolation inicialization
		nIND=2
		nX(1)=Number_of_Points_for_Temperature_Difference
		nX(2)=Number_of_Points_for_Electric_Current		
		nY=2		
		
		
		Do i = 1, Number_Thermoelectric_Cells_in_Series
			! find performance from catalog.
			
			

			X(1)=dT_cell(i) 
			X(2)=Electric_current_to_Thermoelectric_HX
			
			Call InterpolateData(Logical_Unit_for_Performance_Data,nIND,nX,nY,X,Y)
			If (ErrorFound()) Return
			
			
			Qc_cell(i+1)=Y(1)*Thermal_Loss_Coeficient
			U_cell(i+1)=Y(2)*Electric_Loss_Coeficient
			P_cell(i+1)=U_cell(i+1)*I_cell*3.6
			Qh_cell(i+1)=Qc_cell(i+1)+P_cell(i+1)
			
			H_c_cell(i+1)=H_c_cell(i)-Qc_cell(i+1)/M_c_cell
			
				psydat(1)=p_c_cell
				psydat(6)=w_c_cell(i)
				psydat(7)=H_c_cell(i+1)
				Call MoistAirProperties(CurrentUnit,CurrentType,1,7,0,psydat,1,status)
				If (ErrorFound()) Return
			
			T_c_cell(i+1)=psydat(2)
			w_c_cell(i+1)=psydat(6)
			
			H_h_cell(i+1)=H_h_cell(i)+Qh_cell(i+1)/M_h_cell
				psydat(1)=p_h_cell
				psydat(6)=w_h_cell(i)
				psydat(7)=H_h_cell(i+1)
				Call MoistAirProperties(CurrentUnit,CurrentType,1,7,0,psydat,1,status)
				If (ErrorFound()) Return
				
			T_h_cell(i+1)=psydat(2)
			w_h_cell(i+1)=psydat(6)	
			
			!dT_cell(i+1) =DMAX1(0,T_c_cell(i+1)-T_h_cell(i+1))
			dT_cell(i+1)=abs(T_c_cell(i+1)-T_h_cell(i+1))		
	    End do
! --------------End Active HX calculation-----------------------		
		
		
		
		
		If (Thermoelectric_HX_mode_cooling_heating<0.5) Then !cooling/heating mode = 0 - > cooling 
		
			Heat_Transfer_Rate_aHX_sup=sum(Qc_cell)*Number_Thermoelectric_Cells_in_Parallel*-1
			Heat_Transfer_Rate_aHX_exh=sum(Qh_cell)*Number_Thermoelectric_Cells_in_Parallel
			Power_aHX = sum(P_cell)*Number_Thermoelectric_Cells_in_Parallel
			
			
			If (Power_aHX<=0.0) Then
			COP_aHX=0.0 !Heat_Transfer_Rate_aHX_exh/Power_aHX	
			EER_aHX=0.0
			Else
			COP_aHX=0.0 !Heat_Transfer_Rate_aHX_exh/Power_aHX	
			EER_aHX=Heat_Transfer_Rate_aHX_sup/(Power_aHX)
			EndIf
			! Set output air properties
				psydat(1) =p_h_cell
				psydat(6)=w_h_cell(Number_Thermoelectric_Cells_in_Series+1)
				psydat(7)=H_h_cell(Number_Thermoelectric_Cells_in_Series+1)
				Call MoistAirProperties(CurrentUnit,CurrentType,1,7,0,psydat,1,status)
				If (ErrorFound()) Return
			
			Exhaust_Air_Pressure = psydat(1)
			Exhaust_Air_Temperature = psydat(2)
			Exhaust_Air_Relative_Humidity = psydat(4)
			Exhaust_Air_Humidity_Ratio = psydat(6)
			Exhaust_Air_Enthalpy = psydat(7)
			Tdw_pas_exh=psydat(5)

				psydat(1) =p_c_cell
				psydat(6)=w_c_cell(Number_Thermoelectric_Cells_in_Series+1)
				psydat(7)=H_c_cell(Number_Thermoelectric_Cells_in_Series+1)
				Call MoistAirProperties(CurrentUnit,CurrentType,1,7,0,psydat,1,status)
				If (ErrorFound()) Return	

			Supply_Air_Pressure = psydat(1)
			Supply_Air_Temperature = psydat(2)
			Supply_Air_Relative_Humidity = psydat(4)
			Supply_Air_Humidity_Ratio = psydat(6)
		
			Tdw_pas_sup=psydat(5)


			! Set the condensate conditions
			Condensate_Temperature_Sup = Tdw_pas_sup
			Condensate_Flowrate_Sup	 = DMAX1(0.,(Fresh_Air_Flowrate*(Fresh_Air_Humidity_Ratio-Supply_Air_Humidity_Ratio)))

			Condensate_Temperature_Exh = Tdw_pas_exh
			Condensate_Flowrate_Exh	 = DMAX1(0.,(Return_Air_Flowrate*(Return_Air_Humidity_Ratio-Exhaust_Air_Humidity_Ratio)))

		
			
		
		Else !cooling/heating mode = 1 - > heating
		
			
			Heat_Transfer_Rate_aHX_sup=sum(Qh_cell)*Number_Thermoelectric_Cells_in_Parallel
			Heat_Transfer_Rate_aHX_exh=sum(Qc_cell)*Number_Thermoelectric_Cells_in_Parallel*-1
			Power_aHX = sum(P_cell)*Number_Thermoelectric_Cells_in_Parallel
			
			If (Power_aHX<=0.0) Then
			COP_aHX=0.0 !Heat_Transfer_Rate_aHX_exh/Power_aHX	
			EER_aHX=0.0
			Else
			COP_aHX=Heat_Transfer_Rate_aHX_sup/Power_aHX
			EER_aHX= 0.0 !Heat_Transfer_Rate_aHX_exh/Power_aHX	
			EndIf
			
			
			! Set output air properties
				psydat(1) =p_c_cell
				psydat(6)=w_c_cell(Number_Thermoelectric_Cells_in_Series+1)
				psydat(7)=H_c_cell(Number_Thermoelectric_Cells_in_Series+1)
				Call MoistAirProperties(CurrentUnit,CurrentType,1,7,0,psydat,1,status)
				If (ErrorFound()) Return
			
			Exhaust_Air_Pressure = psydat(1)
			Exhaust_Air_Temperature = psydat(2)
			Exhaust_Air_Relative_Humidity = psydat(4)
			Exhaust_Air_Humidity_Ratio = psydat(6)
			Exhaust_Air_Enthalpy = psydat(7)
			Tdw_pas_exh=psydat(5)

				psydat(1) =p_h_cell
				psydat(6)=w_h_cell(Number_Thermoelectric_Cells_in_Series+1)
				psydat(7)=H_h_cell(Number_Thermoelectric_Cells_in_Series+1)
				Call MoistAirProperties(CurrentUnit,CurrentType,1,7,0,psydat,1,status)
				If (ErrorFound()) Return	

			Supply_Air_Pressure = psydat(1)
			Supply_Air_Temperature = psydat(2)
			Supply_Air_Relative_Humidity = psydat(4)
			Supply_Air_Humidity_Ratio = psydat(6)
			Tdw_pas_sup=psydat(5)


			! Set the condensate conditions
			Condensate_Temperature_Sup = Tdw_pas_sup
			Condensate_Flowrate_Sup	 = DMAX1(0.,(Fresh_Air_Flowrate*(Fresh_Air_Humidity_Ratio-Supply_Air_Humidity_Ratio)))

			Condensate_Temperature_Exh = Tdw_pas_exh
			Condensate_Flowrate_Exh	 = DMAX1(0.,(Return_Air_Flowrate*(Return_Air_Humidity_Ratio-Exhaust_Air_Humidity_Ratio)))

		Endif    


!**************************************************************
 ! passive HX is on, the active HX is on
!**************************************************************
	Elseif ((Bypass_signal_heat_recovery_HX< 0.5) .and. ((Bypass_signal_Thermoelectric_HX < 0.5) .and. (Electric_current_to_Thermoelectric_HX > 0.))) Then
	    		
! ------ Calculate the sensible heat transfer based on the effectiveness approach------	
       ! Air stream capacity calculation
        T_K = Return_Air_Temperature+273.15
		P_kPa = Return_Air_Pressure*101.325
		Call AirProp(T_K,P_kPa,airprops)
		cP_exh = airprops(5)
		Cap_exh = cP_exh*Return_Air_Flowrate	
	   


		T_K = Fresh_Air_Temperature+273.15	
		P_kPa = Fresh_Air_Pressure*101.325
		Call AirProp(T_K,P_kPa,airprops)
		cp_pas_sup = airprops(5)
		Cap_pas_sup = cp_pas_sup*Fresh_Air_Flowrate

		Heat_Transfer_Rate_HR = Sensible_Effectiveness*DMIN1(Cap_exh,Cap_pas_sup)*(Return_Air_Temperature-Fresh_Air_Temperature)

! ------ End Calculate the sensible heat transfer based on the effectiveness approach------	
        
		!energy and humidity ratio balance
		H_pas_exh = Return_Air_Enthalpy	- Heat_Transfer_Rate_HR/Return_Air_Flowrate 	! Calculate the enthalpy of the exhaust air stream from an energy balance
	    p_pas_exh = Return_Air_Pressure - Return_Air_Pressure_Drop
		w_pas_exh = Return_Air_Humidity_Ratio !No humidity recovery is considered

		
        H_pas_sup = Fresh_Air_Enthalpy+Heat_Transfer_Rate_HR/Fresh_Air_Flowrate ! Calculate the enthalpy of the fresh air stream from an energy balance
        p_pas_sup = Fresh_Air_Pressure-Fresh_Air_Pressure_Drop
		w_pas_sup = Fresh_Air_Humidity_Ratio 		
		

	    ! Calculate the outlet states
			psydat(1) = p_pas_exh
			psydat(6) = w_pas_exh 
			psydat(7) = H_pas_exh
			Call MoistAirProperties(CurrentUnit,CurrentType,1,7,0,psydat,1,status)
			If (ErrorFound()) Return
		p_pas_exh = psydat(1)
		t_pas_exh = psydat(2)
	    w_pas_exh = psydat(6)
		H_pas_exh = psydat(7)
		

			psydat(1) = p_pas_sup
			psydat(6) = w_pas_sup
			psydat(7) =  H_pas_sup
			Call MoistAirProperties(CurrentUnit,CurrentType,1,7,0,psydat,1,status)
			If (ErrorFound()) Return
		p_pas_sup = psydat(1)
		t_pas_sup = psydat(2)
		w_pas_sup = psydat(6)
		H_pas_sup = psydat(7)

         !Set the outlet heat recovery air properties
		 Heat_Recovery_Outlet_Temperature=psydat(2)
		 Heat_Recovery_Outlet_Humidity_Ratio=psydat(6)
		 Heat_Recovery_Outlet_Relative_Humidity=psydat(4)
	
	    ! Set the condensate conditions
        !Condensate_Temperature_Sup = Tdw_pas_sup
        Cond_Pas_Sup	 = DMAX1(0.,(Fresh_Air_Flowrate*(Fresh_Air_Humidity_Ratio-w_pas_sup)))

        !Condensate_Temperature_Exh = Tdw_pas_exh
        Cond_Pas_Exh	 = DMAX1(0.,(Return_Air_Flowrate*(Return_Air_Humidity_Ratio-w_pas_exh)))
	
! ----------- ---Active HX inicialization ----------------------		
	
		
		If (Thermoelectric_HX_mode_cooling_heating<0.5) Then !cooling/heating mode = 0 - > cooling
			M_c_cell=Fresh_Air_Flowrate/Number_Thermoelectric_Cells_in_Parallel ! massflow over series of cell - even distribution assumption
			p_c_cell= Fresh_Air_Pressure-Fresh_Air_Pressure_Drop		
			H_c_cell(1)=H_pas_sup
			w_c_cell(1)=w_pas_sup
			T_c_cell(1)=t_pas_sup
			
			
			M_h_cell=Return_Air_Flowrate/Number_Thermoelectric_Cells_in_Parallel ! massflow over series of cell - even distribution assumption
			p_h_cell= Return_Air_Pressure - Return_Air_Pressure_Drop
			H_h_cell(1)=H_pas_exh
			w_h_cell(1)=w_pas_exh
			T_h_cell(1)=t_pas_exh
			!dT_cell(1)=DMAX1(0.0,Fresh_Air_Temperature-Return_Air_Temperature)
		
		Else !cooling/heating mode = 1- > heating
		
			M_c_cell=Return_Air_Flowrate/Number_Thermoelectric_Cells_in_Parallel ! massflow over series of cell - even distribution assumption
			p_c_cell= Return_Air_Pressure - Return_Air_Pressure_Drop
			H_c_cell(1)=H_pas_exh
			w_c_cell(1)=w_pas_exh
			T_c_cell(1)=t_pas_exh
			
			
			M_h_cell=Fresh_Air_Flowrate/Number_Thermoelectric_Cells_in_Parallel ! massflow over series of cell - even distribution assumption
			p_h_cell= Fresh_Air_Pressure-Fresh_Air_Pressure_Drop
			H_h_cell(1)=H_pas_sup
			w_h_cell(1)=w_pas_sup
			T_h_cell(1)=t_pas_sup
			!dT_cell(1)=DMAX1(0.0,Return_Air_Temperature-Fresh_Air_Temperature)
		
		Endif
		
		dT_cell(1)=abs(Return_Air_Temperature-Fresh_Air_Temperature)
		I_cell=Electric_current_to_Thermoelectric_HX
		U_cell(1)=0
		P_cell(1)=0
		
		Qc_cell(1)=0
		Qh_cell(1)=0
		
! ----------- ---Active HX calculation-------------------------
		! interpolation inicialization
		nIND=2
		nX(1)=Number_of_Points_for_Temperature_Difference
		nX(2)=Number_of_Points_for_Electric_Current		
		nY=2		
		
		
		Do i = 1, Number_Thermoelectric_Cells_in_Series
			! find performance from catalog.
			
			

			X(1)=dT_cell(i) 
			X(2)=Electric_current_to_Thermoelectric_HX
			
			Call InterpolateData(Logical_Unit_for_Performance_Data,nIND,nX,nY,X,Y)
			If (ErrorFound()) Return
			
			
			Qc_cell(i+1)=Y(1)*Thermal_Loss_Coeficient
			!If Qc_cell<0 Then
			!Qc_cell= 0
			!Endif
			!doplnit kontrolu Qc<0)
			U_cell(i+1)=Y(2)*Electric_Loss_Coeficient
			P_cell(i+1)=U_cell(i+1)*I_cell*3.6
			Qh_cell(i+1)=Qc_cell(i+1)+P_cell(i+1)
			
			H_c_cell(i+1)=H_c_cell(i)-Qc_cell(i+1)/M_c_cell
			
				psydat(1)=p_c_cell
				psydat(6)=w_c_cell(i)
				psydat(7)=H_c_cell(i+1)
				Call MoistAirProperties(CurrentUnit,CurrentType,1,7,0,psydat,1,status)
				If (ErrorFound()) Return
			
			T_c_cell(i+1)=psydat(2)
			w_c_cell(i+1)=psydat(6)
			
			H_h_cell(i+1)=H_h_cell(i)+Qh_cell(i+1)/M_h_cell
				psydat(1)=p_h_cell
				psydat(6)=w_h_cell(i)
				psydat(7)=H_h_cell(i+1)
				Call MoistAirProperties(CurrentUnit,CurrentType,1,7,0,psydat,1,status)
				If (ErrorFound()) Return
				
			T_h_cell(i+1)=psydat(2)
			w_h_cell(i+1)=psydat(6)	
			
			!dT_cell(i+1) =DMAX1(0,T_c_cell(i+1)-T_h_cell(i+1))
			dT_cell(i+1)=abs(T_c_cell(i+1)-T_h_cell(i+1))		
	    Enddo		
! --------------End Active HX calculation-----------		
		
		If (Thermoelectric_HX_mode_cooling_heating<0.5) Then !cooling/heating mode = 0 - > cooling
		
			Heat_Transfer_Rate_aHX_sup=sum(Qc_cell)*Number_Thermoelectric_Cells_in_Parallel*-1
			Heat_Transfer_Rate_aHX_exh=sum(Qh_cell)*Number_Thermoelectric_Cells_in_Parallel
			Power_aHX = sum(P_cell)*Number_Thermoelectric_Cells_in_Parallel
			If (Power_aHX<=0.0) Then
			COP_aHX=0.0 !Heat_Transfer_Rate_aHX_exh/Power_aHX	
			EER_aHX=0.0
			Else
			COP_aHX=0.0 !Heat_Transfer_Rate_aHX_exh/Power_aHX	
			EER_aHX=Heat_Transfer_Rate_aHX_sup/Power_aHX
			EndIf
			
			! Set output air properties
				psydat(1) =p_h_cell
				psydat(6)=w_h_cell(Number_Thermoelectric_Cells_in_Series+1)
				psydat(7)=H_h_cell(Number_Thermoelectric_Cells_in_Series+1)
				Call MoistAirProperties(CurrentUnit,CurrentType,1,7,0,psydat,1,status)
				If (ErrorFound()) Return
			
			Exhaust_Air_Pressure = psydat(1)
			Exhaust_Air_Temperature = psydat(2)
			Exhaust_Air_Relative_Humidity = psydat(4)
			Exhaust_Air_Humidity_Ratio = psydat(6)
			Exhaust_Air_Enthalpy = psydat(7)
			Tdw_pas_exh=psydat(5)

				psydat(1) =p_c_cell
				psydat(6)=w_c_cell(Number_Thermoelectric_Cells_in_Series+1)
				psydat(7)=H_c_cell(Number_Thermoelectric_Cells_in_Series+1)
				Call MoistAirProperties(CurrentUnit,CurrentType,1,7,0,psydat,1,status)
				If (ErrorFound()) Return	

			Supply_Air_Pressure = psydat(1)
			Supply_Air_Temperature = psydat(2)
			Supply_Air_Relative_Humidity = psydat(4)
			Supply_Air_Humidity_Ratio = psydat(6)
		
			Tdw_pas_sup=psydat(5)


			! Set the condensate conditions
			Condensate_Temperature_Sup = Tdw_pas_sup
			Condensate_Flowrate_Sup	 = DMAX1(0.,(Fresh_Air_Flowrate*(Fresh_Air_Humidity_Ratio-Supply_Air_Humidity_Ratio)))

			Condensate_Temperature_Exh = Tdw_pas_exh
			Condensate_Flowrate_Exh	 = DMAX1(0.,(Return_Air_Flowrate*(Return_Air_Humidity_Ratio-Exhaust_Air_Humidity_Ratio)))

		
			
		
		Else !cooling/heating mode = 1 - > heating
		
			
			Heat_Transfer_Rate_aHX_sup=sum(Qh_cell)*Number_Thermoelectric_Cells_in_Parallel
			Heat_Transfer_Rate_aHX_exh=sum(Qc_cell)*Number_Thermoelectric_Cells_in_Parallel*-1
			Power_aHX = sum(P_cell)*Number_Thermoelectric_Cells_in_Parallel
			If (Power_aHX<=0.0) Then
			COP_aHX=0.0 !Heat_Transfer_Rate_aHX_exh/Power_aHX	
			EER_aHX=0.0
			Else
			COP_aHX=Heat_Transfer_Rate_aHX_sup/Power_aHX
			EER_aHX= 0.0 !Heat_Transfer_Rate_aHX_exh/Power_aHX	
			EndIf
			
			! Set output air properties
				psydat(1) =p_c_cell
				psydat(6)=w_c_cell(Number_Thermoelectric_Cells_in_Series+1)
				psydat(7)=H_c_cell(Number_Thermoelectric_Cells_in_Series+1)
				Call MoistAirProperties(CurrentUnit,CurrentType,1,7,0,psydat,1,status)
				If (ErrorFound()) Return
			
			Exhaust_Air_Pressure = psydat(1)
			Exhaust_Air_Temperature = psydat(2)
			Exhaust_Air_Relative_Humidity = psydat(4)
			Exhaust_Air_Humidity_Ratio = psydat(6)
			Exhaust_Air_Enthalpy = psydat(7)
			Tdw_pas_exh=psydat(5)

				psydat(1) =p_h_cell
				psydat(6)=w_h_cell(Number_Thermoelectric_Cells_in_Series+1)
				psydat(7)=H_h_cell(Number_Thermoelectric_Cells_in_Series+1)
				Call MoistAirProperties(CurrentUnit,CurrentType,1,7,0,psydat,1,status)
				If (ErrorFound()) Return	

			Supply_Air_Pressure = psydat(1)
			Supply_Air_Temperature = psydat(2)
			Supply_Air_Relative_Humidity = psydat(4)
			Supply_Air_Humidity_Ratio = psydat(6)
			Tdw_pas_sup=psydat(5)


			! Set the condensate conditions
			Condensate_Temperature_Sup = Tdw_pas_sup
			Condensate_Flowrate_Sup	 = DMAX1(0.,(Fresh_Air_Flowrate*(Fresh_Air_Humidity_Ratio-Supply_Air_Humidity_Ratio)))+Cond_Pas_Sup

			Condensate_Temperature_Exh = Tdw_pas_exh
			Condensate_Flowrate_Exh	 = DMAX1(0.,(Return_Air_Flowrate*(Return_Air_Humidity_Ratio-Exhaust_Air_Humidity_Ratio)))+Cond_Pas_Exh

		
		Endif
	EndIf
	
	


 EndIf

!-----------------------------------------------------------------------------------------------------------------------
!Set the Outputs from this Model (#,Value)
		Call SetOutputValue(1,Exhaust_Air_Temperature)
		Call SetOutputValue(2,Exhaust_Air_Humidity_Ratio)
		Call SetOutputValue(3,Exhaust_Air_Relative_Humidity*100.)
		Call SetOutputValue(4,Return_Air_Flowrate)
		Call SetOutputValue(5,Exhaust_Air_Pressure)
		Call SetOutputValue(6,Supply_Air_Temperature)
		Call SetOutputValue(7,Supply_Air_Humidity_Ratio)
		Call SetOutputValue(8,Supply_Air_Relative_Humidity*100.)
		Call SetOutputValue(9,Fresh_Air_Flowrate)
		Call SetOutputValue(10,Supply_Air_Pressure)
		Call SetOutputValue(11,Heat_Transfer_Rate_HR)
		Call SetOutputValue(12,Heat_Transfer_Rate_aHX_sup) ! Heat Transfer Rate to Supply Air - Thermoelectric HX 
		Call SetOutputValue(13,Heat_Transfer_Rate_aHX_exh) ! Heat Transfer Rate to Exhaust Air - Thermoelectric HX
		Call SetOutputValue(14, Power_aHX ) ! Power - Thermoelectric HX
		Call SetOutputValue(15,COP_aHX) ! COP - Thermoelectric HX
		Call SetOutputValue(16,EER_aHX) ! EER - Thermoelectric HX
		Call SetOutputValue(17, Condensate_Temperature_Exh) ! Condensate Temperature - Exhaust Stream
		Call SetOutputValue(18, Condensate_Flowrate_Exh) ! Condensate Flowrate - Exhaust Stream
		Call SetOutputValue(19, Condensate_Temperature_Sup) ! Condensate Temperature - Supply Air Stream
		Call SetOutputValue(20, Condensate_Flowrate_Sup) ! Condensate Flowrate - Supply Air Stream
		Call SetOutputValue(21, Heat_Recovery_Outlet_Temperature) !	Heat Recovery Outlet Temperature	C [-Inf;+Inf]
		Call SetOutputValue(22, Heat_Recovery_Outlet_Humidity_Ratio) ! Heat Recovery Outlet Humidity Ratio	- [0.0;+Inf]
		Call SetOutputValue(23, Heat_Recovery_Outlet_Relative_Humidity*100.) ! Heat Recovery Outlet % Relative Humidity	- [0.0;100.0]
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!If Needed, Store the Desired Disceret Control Signal Values for this Iteration (#,State)
!Sample Code:  Call SetDesiredDiscreteControlState(1,1)
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!If Needed, Store the Final value of the Dynamic Variables in the Global Storage Array (#,Value)
!Sample Code:  Call SetDynamicArrayValueThisIteration(1,T_FINAL_1)
!-----------------------------------------------------------------------------------------------------------------------
 
      Return
      End
!-----------------------------------------------------------------------------------------------------------------------

