      Subroutine Type230

! Object: Thermoelectric Ventilation Unit Controller
! Simulation Studio Model: Type230
! 

! Author: Vojtech  Zavrel
! Editor: Vojtech  Zavrel
! Date:	 05/12/ 2021
! last modified: 04/08/2022
! 
! 
! *** 
! *** Model Parameters 
! *** 
!			Mode - Active HX	- [0;4]
!			Mode - Fans	- [0;1]
!			Rated Unit Electric Current	- [0;+Inf]
!			Rated Unit Flowrate	- [0;+Inf]

! *** 
! *** Model Inputs 
! *** 
!			Sensor Fresh Air Temperature	C [-Inf;+Inf]
!			Sensor Return Air Temperature	C [-Inf;+Inf]
!			Sensor Supply Air Temperature	C [-Inf;+Inf]
!			Sensor Exhaust Air Temperature	C [-Inf;+Inf]
!			Sensor Heat Recovery Outlet Temperature	C [-Inf;+Inf]
!			Setpoint Supply Air Temperature	C [-Inf;+Inf]
!			Deadband for Supply air temperature	deltaC [1;+Inf]
!			Upper Comfort Boundery Temperature	C [-Inf;+Inf]
!			Lower Comfort Boundery Temperature	C [-Inf;+Inf]
!			General On/Off	- [0;1]
!			Schedule Occupancy	- [0;+Inf]
!			Schedule Fans	- [0;+Inf]
!			PID-Control Signal	- [-Inf;+Inf]
!			PID-Gain tunning ratio	- [-Inf;+Inf]
!			PID-Integral time tunnig ratio	- [-Inf;+Inf]

! *** 
! *** Model Outputs 
! *** 
!			Unit On/Off	- [0;1]
!			Electric Current to Thermoelectric	amperes [0;+Inf]
!			Thermoelectric HX Mode - Cooling/Heating	- [0;1]
!			Bypass signal - Heat Recovery HX	- [0;1]
!			Bypass signal - Thermoelectric HX	- [0;1]
!			Fan Control Signal	- [0;1]
!			PID-Setpoint	- [-Inf;+Inf]
!			PID-Controlled variable	- [-Inf;+Inf]
!			PID-Minimum control signal	- [-Inf;+Inf]
!			PID-Maximum control signal	- [-Inf;+Inf]
!			PID-Threshold for non-zero output	- [-Inf;+Inf]
!			PID-Gain constant	- [-Inf;+Inf]
!			PID-Integral time	- [-Inf;+Inf]
!			PID-Derivative time	- [-Inf;+Inf]

! *** 
! *** Model Derivatives 
! *** 

! (Comments and routine interface generated by TRNSYS Simulation Studio)
!************************************************************************

!-----------------------------------------------------------------------------------------------------------------------
! This TRNSYS component skeleton was generated from the TRNSYS studio based on the user-supplied parameters, inputs, 
! outputs, and derivatives.  The user should check the component formulation carefully and add the content to transform
! the parameters, inputs and derivatives into outputs.  Remember, outputs should be the average value over the timestep
! and not the value at the end of the timestep; although in many models these are exactly the same values.  Refer to 
! existing types for examples of using advanced features inside the model (Formats, Labels etc.)
!-----------------------------------------------------------------------------------------------------------------------


      Use TrnsysConstants
      Use TrnsysFunctions

!-----------------------------------------------------------------------------------------------------------------------

!DEC$Attributes DLLexport :: Type222

!-----------------------------------------------------------------------------------------------------------------------
!Trnsys Declarations
      Implicit None

      Double Precision Timestep,Time
      Integer CurrentUnit,CurrentType


!    PARAMETERS
      Integer Mode_Active_HX
      Integer Mode_Fans
      DOUBLE PRECISION Rated_Unit_Electric_Current
      DOUBLE PRECISION Rated_Unit_Flowrate

!    INPUTS
      DOUBLE PRECISION Sensor_Fresh_Air_Temperature
      DOUBLE PRECISION Sensor_Return_Air_Temperature
      DOUBLE PRECISION Sensor_Supply_Air_Temperature
      DOUBLE PRECISION Sensor_Exhaust_Air_Temperature
      DOUBLE PRECISION Sensor_Heat_Recovery_Outlet_Temperature
      DOUBLE PRECISION Setpoint_Supply_Air_Temperature
      DOUBLE PRECISION Deadband_for_Supply_air_temperature
      DOUBLE PRECISION Upper_Comfort_Boundery_Temperature
      DOUBLE PRECISION Lower_Comfort_Boundery_Temperature
      DOUBLE PRECISION General_On_Off
      DOUBLE PRECISION Schedule_Occupancy
      DOUBLE PRECISION Schedule_Fans
      DOUBLE PRECISION PID_Control_Signal
      DOUBLE PRECISION PID_Gain_tunning_ratio
      DOUBLE PRECISION PID_Integral_time_tunnig_ratio
!    OUTPUTS
     DOUBLE PRECISION Unit_OnOff
	 DOUBLE PRECISION Electric_Current_to_Thermoelectric
	 DOUBLE PRECISION Thermoelectric_Cooling_Heating
	 DOUBLE PRECISION Bypass_signal_Heat_Recovery_HX
	 DOUBLE PRECISION Bypass_signal_Thermoelectric_HX
	 DOUBLE PRECISION Fan_Control_Signal
	 DOUBLE PRECISION PID_Setpoint
	 DOUBLE PRECISION PID_Controlled_Variable
	 DOUBLE PRECISION PID_OnOff
	 DOUBLE PRECISION PID_Max_Ctrl
	 DOUBLE PRECISION PID_Min_Ctrl
	 DOUBLE PRECISION PID_Threshold
	 DOUBLE PRECISION PID_Gain
	 DOUBLE PRECISION PID_Integral_Time
!    AUXILARY


!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Get the Global Trnsys Simulation Variables
      Time=getSimulationTime()
      Timestep=getSimulationTimeStep()
      CurrentUnit = getCurrentUnit()
      CurrentType = getCurrentType()
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Set the Version Number for This Type
      If(getIsVersionSigningTime()) Then
		Call SetTypeVersion(17)
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do Any Last Call Manipulations Here
      If(getIsLastCallofSimulation()) Then
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Perform Any "After Convergence" Manipulations That May Be Required at the End of Each Timestep
      If(getIsEndOfTimestep()) Then
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do All of the "Very First Call of the Simulation Manipulations" Here
      If(getIsFirstCallofSimulation()) Then

		!Tell the TRNSYS Engine How This Type Works
		Call SetNumberofParameters(4)           !The number of parameters that the the model wants
		Call SetNumberofInputs(15)                   !The number of inputs that the the model wants
		Call SetNumberofDerivatives(0)         !The number of derivatives that the the model wants
		Call SetNumberofOutputs(15)                 !The number of outputs that the the model produces
		Call SetIterationMode(1)                             !An indicator for the iteration mode (default=1).  Refer to section 8.4.3.5 of the documentation for more details.
		Call SetNumberStoredVariables(0,0)                   !The number of static variables that the model wants stored in the global storage array and the number of dynamic variables that the model wants stored in the global storage array
		Call SetNumberofDiscreteControls(0)               !The number of discrete control functions set by this model (a value greater than zero requires the user to use Solver 1: Powell's method)

		Return

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do All of the First Timestep Manipulations Here - There Are No Iterations at the Intial Time
      If (getIsStartTime()) Then
      Mode_Active_HX = getParameterValue(1)
      Mode_Fans = getParameterValue(2)
      Rated_Unit_Electric_Current = getParameterValue(3)
      Rated_Unit_Flowrate = getParameterValue(4)


      Sensor_Fresh_Air_Temperature = GetInputValue(1)
      Sensor_Return_Air_Temperature = GetInputValue(2)
      Sensor_Supply_Air_Temperature = GetInputValue(3)
      Sensor_Exhaust_Air_Temperature = GetInputValue(4)
      Sensor_Heat_Recovery_Outlet_Temperature = GetInputValue(5)
      Setpoint_Supply_Air_Temperature = GetInputValue(6)
      Deadband_for_Supply_air_temperature = GetInputValue(7)
      Upper_Comfort_Boundery_Temperature = GetInputValue(8)
      Lower_Comfort_Boundery_Temperature = GetInputValue(9)
      General_On_Off = GetInputValue(10)
      Schedule_Occupancy = GetInputValue(11)
      Schedule_Fans = GetInputValue(12)
      PID_Control_Signal = GetInputValue(13)
      PID_Gain_tunning_ratio = GetInputValue(14)
      PID_Integral_time_tunnig_ratio = GetInputValue(15)

	
   !Check the Parameters for Problems (#,ErrorType,Text)
   !Sample Code: If( PAR1 <= 0.) Call FoundBadParameter(1,'Fatal','The first parameter provided to this model is not acceptable.')
  

     If (Rated_Unit_Electric_Current <= 0.d0) Call FoundBadParameter(3,'fatal','The parameter "Rated Electric Current" must be positive.')
     If (Rated_Unit_Flowrate <= 0.d0) Call FoundBadParameter(4,'fatal','The parameter "Rated Electric Current" must be positive.')
    
   !Set the Initial Values of the Outputs (#,Value)
		Call SetOutputValue(1, 0.d0) ! Unit On/Off
		Call SetOutputValue(2, 0.d0) ! Electric Current to Thermoelectric
		Call SetOutputValue(3, 0.d0) ! Thermoelectric HX Mode - Cooling/Heating
		Call SetOutputValue(4, 0.d0) ! Bypass signal - Heat Recovery HX
		Call SetOutputValue(5, 0.d0) ! Bypass signal - Thermoelectric HX
		Call SetOutputValue(6, 0.d0) ! Fan Control Signal
		Call SetOutputValue(7, 0.d0) ! PID-Setpoint
		Call SetOutputValue(8, 0.d0) ! PID-Controlled variable
		Call SetOutputValue(9, 0.d0) ! PID-ON/OFF
		Call SetOutputValue(10, 0.d0) ! PID-Minimum control signal
		Call SetOutputValue(11, 0.d0) ! PID-Maximum control signal
		Call SetOutputValue(12, 0.d0) ! PID-Threshold for non-zero output
		Call SetOutputValue(13, 0.d0) ! PID-Gain constant
		Call SetOutputValue(14, 0.d0) ! PID-Integral time
		Call SetOutputValue(15, 0.d0) ! PID-Derivative time

	
   !If Needed, Set the Initial Values of the Static Storage Variables (#,Value)
   !Sample Code: SetStaticArrayValue(1,0.d0)

   !If Needed, Set the Initial Values of the Dynamic Storage Variables (#,Value)
   !Sample Code: Call SetDynamicArrayValueThisIteration(1,20.d0)

   !If Needed, Set the Initial Values of the Discrete Controllers (#,Value)
   !Sample Code for Controller 1 Set to Off: Call SetDesiredDiscreteControlState(1,0) 

		Return

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!ReRead the Parameters if Another Unit of This Type Has Been Called Last
      If(getIsReReadParameters()) Then
		!Read in the Values of the Parameters from the Input File
      Mode_Active_HX = getParameterValue(1)
      Mode_Fans = getParameterValue(2)
      Rated_Unit_Electric_Current = getParameterValue(3)
      Rated_Unit_Flowrate = getParameterValue(4)

		
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!Read the Inputs
      Sensor_Fresh_Air_Temperature = GetInputValue(1)
      Sensor_Return_Air_Temperature = GetInputValue(2)
      Sensor_Supply_Air_Temperature = GetInputValue(3)
      Sensor_Exhaust_Air_Temperature = GetInputValue(4)
      Sensor_Heat_Recovery_Outlet_Temperature = GetInputValue(5)
      Setpoint_Supply_Air_Temperature = GetInputValue(6)
      Deadband_for_Supply_air_temperature = GetInputValue(7)
      Upper_Comfort_Boundery_Temperature = GetInputValue(8)
      Lower_Comfort_Boundery_Temperature = GetInputValue(9)
      General_On_Off = GetInputValue(10)
      Schedule_Occupancy = GetInputValue(11)
      Schedule_Fans = GetInputValue(12)
      PID_Control_Signal = GetInputValue(13)
      PID_Gain_tunning_ratio = GetInputValue(14)
      PID_Integral_time_tunnig_ratio = GetInputValue(15)
		

	!Check the Inputs for Problems (#,ErrorType,Text)
	!Sample Code: If( IN1 <= 0.) Call FoundBadInput(1,'Fatal','The first input provided to this model is not acceptable.')
      If (Upper_Comfort_Boundery_Temperature <= Lower_Comfort_Boundery_Temperature) Call FoundBadInput(8,'fatal','The parameter "Upper Comfort Boundary Temperature" must be higher than "Lower Comfort Boundary"')
      If(ErrorFound()) Return
!-----------------------------------------------------------------------------------------------------------------------
!-----------------------------------------------------------------------------------------------------------------------
!    *** PERFORM ALL THE CALCULATION HERE FOR THIS MODEL. ***
!-----------------------------------------------------------------------------------------------------------------------
    ! General off	
If (General_On_Off<=0) Then
Unit_OnOff=0.0
Electric_Current_to_Thermoelectric=0.0
Thermoelectric_Cooling_Heating=0.0
Bypass_signal_Heat_Recovery_HX=1.0
Bypass_signal_Thermoelectric_HX=1.0
Fan_Control_Signal=0.0
PID_Setpoint=0.0
PID_Controlled_Variable=0.0
PID_OnOff=0
PID_Min_Ctrl=0
PID_Max_Ctrl=1
PID_Threshold=0
PID_Gain=0.1
PID_Integral_Time=1/60



Else
! **********************************************************************************************************************
! ventilation mode, both active and passive HX are in operation to precisily control supply temperature
! Direct fan control
! **********************************************************************************************************************	

	If ((Mode_Active_HX == 1) .and. (Mode_Fans == 1)) Then ! ventilation mode, both active and passive HX are in operation to precisily control supply temperature
	Unit_OnOff=1
	Electric_Current_to_Thermoelectric=PID_Control_Signal*Rated_Unit_Electric_Current
	    !aHX control 
		If (((Setpoint_Supply_Air_Temperature+Deadband_for_Supply_air_temperature)-Sensor_Heat_Recovery_Outlet_Temperature)<=0) Then !aHX cooling
		
			Thermoelectric_Cooling_Heating=0.0
			PID_Setpoint=Setpoint_Supply_Air_Temperature+Deadband_for_Supply_air_temperature
			PID_Controlled_Variable=Sensor_Supply_Air_Temperature
			PID_OnOff=1
			PID_Min_Ctrl=0
			PID_Max_Ctrl=1
			PID_Threshold=0
			PID_Gain=-0.1*PID_Gain_tunning_ratio
			PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
		
		ElseIf ((Setpoint_Supply_Air_Temperature-Sensor_Heat_Recovery_Outlet_Temperature)>=0) Then !aHX heating
			
			Thermoelectric_Cooling_Heating=1.0
			PID_Setpoint=Setpoint_Supply_Air_Temperature
			PID_Controlled_Variable=Sensor_Supply_Air_Temperature
			PID_OnOff=1
			PID_Min_Ctrl=0
			PID_Max_Ctrl=1
			PID_Threshold=0
			PID_Gain=0.1*PID_Gain_tunning_ratio
			PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
		
		Else !aHX heating
		
			Thermoelectric_Cooling_Heating=1.0
			PID_Setpoint=Setpoint_Supply_Air_Temperature
			PID_Controlled_Variable=Sensor_Supply_Air_Temperature
			PID_OnOff=0
			PID_Min_Ctrl=0
			PID_Max_Ctrl=1
			PID_Threshold=0
			PID_Gain=0.1*PID_Gain_tunning_ratio
			PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
			
		Endif
	    
		
		!bypass control
		If ((Sensor_Fresh_Air_Temperature>Lower_Comfort_Boundery_Temperature) .and. (Sensor_Fresh_Air_Temperature<Upper_Comfort_Boundery_Temperature)) Then
	    Bypass_signal_Heat_Recovery_HX=1.0
	    Bypass_signal_Thermoelectric_HX=1.0
		Else
		Bypass_signal_Heat_Recovery_HX=0.0
	    Bypass_signal_Thermoelectric_HX=0.0
	    EndIf

		!fan control
		Fan_Control_Signal= Schedule_Fans
		!Fan_Control_Signal= DMIN1(Schedule_Occupancy*25*1.2/Rated_Unit_Flowrate,1.0)
! **********************************************************************************************************************
! discomfort hours mitigation mode, both active and passive HX are in operation for cooling and heating purposes
! **********************************************************************************************************************	
	ElseIf	((Mode_Active_HX == 2) .and. (Mode_Fans == 1)) Then 
	Unit_OnOff=1
	Electric_Current_to_Thermoelectric=PID_Control_Signal*Rated_Unit_Electric_Current
	    
		If ((Sensor_Return_Air_Temperature>Lower_Comfort_Boundery_Temperature) .and. (Sensor_Return_Air_Temperature<Upper_Comfort_Boundery_Temperature)) Then ! ventilation mode
		!aHX control 
		
			If (((Setpoint_Supply_Air_Temperature+Deadband_for_Supply_air_temperature)-Sensor_Heat_Recovery_Outlet_Temperature)<0) Then !aHX cooling
			
				Thermoelectric_Cooling_Heating=0.0
				PID_Setpoint=Setpoint_Supply_Air_Temperature+Deadband_for_Supply_air_temperature
				PID_Controlled_Variable=Sensor_Supply_Air_Temperature
				PID_OnOff=1
				PID_Min_Ctrl=0
				PID_Max_Ctrl=1
				PID_Threshold=0
				PID_Gain=-0.1*PID_Gain_tunning_ratio
				PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
			
			ElseIf ((Setpoint_Supply_Air_Temperature-Sensor_Heat_Recovery_Outlet_Temperature)>0) Then !aHX heating
				
				Thermoelectric_Cooling_Heating=1.0
				PID_Setpoint=Setpoint_Supply_Air_Temperature
				PID_Controlled_Variable=Sensor_Supply_Air_Temperature
				PID_OnOff=1
				PID_Min_Ctrl=0
				PID_Max_Ctrl=1
				PID_Threshold=0
				PID_Gain=0.1*PID_Gain_tunning_ratio
				PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
			
			Else !no aHX conditioning
			
				Thermoelectric_Cooling_Heating=1.0
				PID_Setpoint=Setpoint_Supply_Air_Temperature
				PID_Controlled_Variable=Sensor_Supply_Air_Temperature
				PID_OnOff=0
				PID_Min_Ctrl=0
				PID_Max_Ctrl=1
				PID_Threshold=0
				PID_Gain=0.1*PID_Gain_tunning_ratio
				PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
				
			Endif
			
			
			!bypass control
			If ((Sensor_Fresh_Air_Temperature>Lower_Comfort_Boundery_Temperature) .and. (Sensor_Fresh_Air_Temperature<Upper_Comfort_Boundery_Temperature)) Then
			Bypass_signal_Heat_Recovery_HX=1.0
			Bypass_signal_Thermoelectric_HX=1.0
			Else
			Bypass_signal_Heat_Recovery_HX=0.0
			Bypass_signal_Thermoelectric_HX=0.0
			EndIf

			!fan control
			Fan_Control_Signal= Schedule_Fans
			!Fan_Control_Signal= DMIN1(Schedule_Occupancy*25*1.2/Rated_Unit_Flowrate,1.0)
		Else ! discomfort mitigation mode
			
			
			!aHX control
			If ((Upper_Comfort_Boundery_Temperature-Sensor_Return_Air_Temperature)<0) Then !aHX cooling
			
				Thermoelectric_Cooling_Heating=0.0
				PID_Setpoint=Upper_Comfort_Boundery_Temperature
				PID_Controlled_Variable=Sensor_Return_Air_Temperature
				PID_OnOff=1
				PID_Min_Ctrl=0
				PID_Max_Ctrl=1
				PID_Threshold=0
				PID_Gain=-0.1*PID_Gain_tunning_ratio
				PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
			
			ElseIf ((Lower_Comfort_Boundery_Temperature-Sensor_Return_Air_Temperature)>0) Then !aHX heating
				
				Thermoelectric_Cooling_Heating=1.0
				PID_Setpoint=Setpoint_Supply_Air_Temperature
				PID_Controlled_Variable=Sensor_Supply_Air_Temperature
				PID_OnOff=1
				PID_Min_Ctrl=0
				PID_Max_Ctrl=1
				PID_Threshold=0
				PID_Gain=0.1*PID_Gain_tunning_ratio
				PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
			
			Else !aHX heating
			
				Thermoelectric_Cooling_Heating=1.0
				PID_Setpoint=Setpoint_Supply_Air_Temperature
				PID_Controlled_Variable=Sensor_Supply_Air_Temperature
				PID_OnOff=0
				PID_Min_Ctrl=0
				PID_Max_Ctrl=1
				PID_Threshold=0
				PID_Gain=0.1*PID_Gain_tunning_ratio
				PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
				
			Endif
			!bypass control
		    If ((Sensor_Fresh_Air_Temperature>Lower_Comfort_Boundery_Temperature) .and. (Sensor_Fresh_Air_Temperature<Upper_Comfort_Boundery_Temperature)) Then
			Bypass_signal_Heat_Recovery_HX=1.0
			Bypass_signal_Thermoelectric_HX=1.0
			Else
			Bypass_signal_Heat_Recovery_HX=0.0
			Bypass_signal_Thermoelectric_HX=0.0
			EndIf
			!fan control
			If (Schedule_Occupancy<=0) Then
			Fan_Control_Signal=1
			Else
			Fan_Control_Signal= DMIN1(Schedule_Occupancy*30*1.2/Rated_Unit_Flowrate,1.0)		
			EndIf
	EndIf		
		
	!***********************************************************************************************************************
	! overcooling hours mitigation mode, both active and passive HX are in operation for cooling purposes 
	!***********************************************************************************************************************

	ElseIf	((Mode_Active_HX == 3) .and. (Mode_Fans == 1)) Then 
	
		Unit_OnOff=1
	Electric_Current_to_Thermoelectric=PID_Control_Signal*Rated_Unit_Electric_Current
	    
		If (Sensor_Return_Air_Temperature<Upper_Comfort_Boundery_Temperature) Then ! ventilation mode
		!aHX control 
		
			If (((Setpoint_Supply_Air_Temperature+Deadband_for_Supply_air_temperature)-Sensor_Heat_Recovery_Outlet_Temperature)<0) Then !aHX cooling
			
				Thermoelectric_Cooling_Heating=0.0
				PID_Setpoint=Setpoint_Supply_Air_Temperature+Deadband_for_Supply_air_temperature
				PID_Controlled_Variable=Sensor_Supply_Air_Temperature
				PID_OnOff=1
				PID_Min_Ctrl=0
				PID_Max_Ctrl=1
				PID_Threshold=0
				PID_Gain=-0.1*PID_Gain_tunning_ratio
				PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
			
			ElseIf ((Setpoint_Supply_Air_Temperature-Sensor_Heat_Recovery_Outlet_Temperature)>0) Then !aHX heating
				
				Thermoelectric_Cooling_Heating=1.0
				PID_Setpoint=Setpoint_Supply_Air_Temperature
				PID_Controlled_Variable=Sensor_Supply_Air_Temperature
				PID_OnOff=1
				PID_Min_Ctrl=0
				PID_Max_Ctrl=1
				PID_Threshold=0
				PID_Gain=0.1*PID_Gain_tunning_ratio
				PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
			
			Else !no aHX conditioning
			
				Thermoelectric_Cooling_Heating=1.0
				PID_Setpoint=Setpoint_Supply_Air_Temperature
				PID_Controlled_Variable=Sensor_Supply_Air_Temperature
				PID_OnOff=0
				PID_Min_Ctrl=0
				PID_Max_Ctrl=1
				PID_Threshold=0
				PID_Gain=0.1*PID_Gain_tunning_ratio
				PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
				
			Endif
			
			
			!bypass control
			If ((Sensor_Fresh_Air_Temperature>Lower_Comfort_Boundery_Temperature) .and. (Sensor_Fresh_Air_Temperature<Upper_Comfort_Boundery_Temperature)) Then
			Bypass_signal_Heat_Recovery_HX=1.0
			Bypass_signal_Thermoelectric_HX=1.0
			Else
			Bypass_signal_Heat_Recovery_HX=0.0
			Bypass_signal_Thermoelectric_HX=0.0
			EndIf

			!fan control
			Fan_Control_Signal= Schedule_Fans
			!Fan_Control_Signal= DMIN1(Schedule_Occupancy*25*1.2/Rated_Unit_Flowrate,1.0)
		Else ! discomfort mitigation mode
			
			
			!aHX control
			!aHX cooling			
				Thermoelectric_Cooling_Heating=0.0
				PID_Setpoint=Upper_Comfort_Boundery_Temperature
				PID_Controlled_Variable=Sensor_Return_Air_Temperature
				PID_OnOff=1
				PID_Min_Ctrl=0
				PID_Max_Ctrl=1
				PID_Threshold=0
				PID_Gain=-0.1*PID_Gain_tunning_ratio
				PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
			

			!bypass control
		    If ((Sensor_Fresh_Air_Temperature>Lower_Comfort_Boundery_Temperature) .and. (Sensor_Fresh_Air_Temperature<Upper_Comfort_Boundery_Temperature)) Then
			Bypass_signal_Heat_Recovery_HX=1.0
			Bypass_signal_Thermoelectric_HX=1.0
			Else
			Bypass_signal_Heat_Recovery_HX=0.0
			Bypass_signal_Thermoelectric_HX=0.0
			EndIf
			!fan control
			If (Schedule_Occupancy<=0) Then
			Fan_Control_Signal=1
			Else
			Fan_Control_Signal= DMIN1(Schedule_Occupancy*30*1.2/Rated_Unit_Flowrate,1.0)		
			EndIf
	EndIf	
	
	!***********************************************************************************************************************
	! underheating hours mitigation mode, both active and passive HX are in operation for heating purposes 
	!***********************************************************************************************************************
	ElseIf	((Mode_Active_HX == 4) .and. (Mode_Fans == 1))  Then 
		Unit_OnOff=1
	    Electric_Current_to_Thermoelectric=PID_Control_Signal*Rated_Unit_Electric_Current
	    
		If ((Sensor_Return_Air_Temperature>Lower_Comfort_Boundery_Temperature)) Then ! ventilation mode
		!aHX control 
		
			If (((Setpoint_Supply_Air_Temperature+Deadband_for_Supply_air_temperature)-Sensor_Heat_Recovery_Outlet_Temperature)<0) Then !aHX cooling
			
				Thermoelectric_Cooling_Heating=0.0
				PID_Setpoint=Setpoint_Supply_Air_Temperature+Deadband_for_Supply_air_temperature
				PID_Controlled_Variable=Sensor_Supply_Air_Temperature
				PID_OnOff=1
				PID_Min_Ctrl=0
				PID_Max_Ctrl=1
				PID_Threshold=0
				PID_Gain=-0.1*PID_Gain_tunning_ratio
				PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
			
			ElseIf ((Setpoint_Supply_Air_Temperature-Sensor_Heat_Recovery_Outlet_Temperature)>0) Then !aHX heating
				
				Thermoelectric_Cooling_Heating=1.0
				PID_Setpoint=Setpoint_Supply_Air_Temperature
				PID_Controlled_Variable=Sensor_Supply_Air_Temperature
				PID_OnOff=1
				PID_Min_Ctrl=0
				PID_Max_Ctrl=1
				PID_Threshold=0
				PID_Gain=0.1*PID_Gain_tunning_ratio
				PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
			
			Else !no aHX conditioning
			
				Thermoelectric_Cooling_Heating=1.0
				PID_Setpoint=Setpoint_Supply_Air_Temperature
				PID_Controlled_Variable=Sensor_Supply_Air_Temperature
				PID_OnOff=0
				PID_Min_Ctrl=0
				PID_Max_Ctrl=1
				PID_Threshold=0
				PID_Gain=0.1*PID_Gain_tunning_ratio
				PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
				
			Endif
			
			
			!bypass control
			If ((Sensor_Fresh_Air_Temperature>Lower_Comfort_Boundery_Temperature) .and. (Sensor_Fresh_Air_Temperature<Upper_Comfort_Boundery_Temperature)) Then
			Bypass_signal_Heat_Recovery_HX=1.0
			Bypass_signal_Thermoelectric_HX=1.0
			Else
			Bypass_signal_Heat_Recovery_HX=0.0
			Bypass_signal_Thermoelectric_HX=0.0
			EndIf

			!fan control
			Fan_Control_Signal= Schedule_Fans
			!Fan_Control_Signal= DMIN1(Schedule_Occupancy*25*1.2/Rated_Unit_Flowrate,1.0)
		Else ! discomfort mitigation mode
			
			
			!aHX control
			!aHX heating
				
				Thermoelectric_Cooling_Heating=1.0
				PID_Setpoint=Setpoint_Supply_Air_Temperature
				PID_Controlled_Variable=Sensor_Supply_Air_Temperature
				PID_OnOff=1
				PID_Min_Ctrl=0
				PID_Max_Ctrl=1
				PID_Threshold=0
				PID_Gain=0.1*PID_Gain_tunning_ratio
				PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
			
			
			!bypass control
		    If ((Sensor_Fresh_Air_Temperature>Lower_Comfort_Boundery_Temperature) .and. (Sensor_Fresh_Air_Temperature<Upper_Comfort_Boundery_Temperature)) Then
			Bypass_signal_Heat_Recovery_HX=1.0
			Bypass_signal_Thermoelectric_HX=1.0
			Else
			Bypass_signal_Heat_Recovery_HX=0.0
			Bypass_signal_Thermoelectric_HX=0.0
			EndIf
			!fan control
			If (Schedule_Occupancy<=0) Then
			Fan_Control_Signal=1
			Else
			Fan_Control_Signal= DMIN1(Schedule_Occupancy*30*1.2/Rated_Unit_Flowrate,1.0)		
			EndIf
	EndIf	
	
	!***********************************************************************************************************************
	! only passive heat recovery is considered, no active operation is considered 
	!***********************************************************************************************************************
	ElseIf	 ((Mode_Active_HX == 0) .and. (Mode_Fans == 1)) Then 
			Unit_OnOff=1
	        Electric_Current_to_Thermoelectric=PID_Control_Signal*Rated_Unit_Electric_Current
			!aHX control -off
	        Thermoelectric_Cooling_Heating=1.0
			PID_Setpoint=Setpoint_Supply_Air_Temperature
			PID_Controlled_Variable=Sensor_Supply_Air_Temperature
			PID_OnOff=0
			PID_Min_Ctrl=0
			PID_Max_Ctrl=1
			PID_Threshold=0
			PID_Gain=0.1*PID_Gain_tunning_ratio
			PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
			!bypass control
		    If ((Sensor_Fresh_Air_Temperature>Lower_Comfort_Boundery_Temperature) .and. (Sensor_Fresh_Air_Temperature<Upper_Comfort_Boundery_Temperature)) Then
			Bypass_signal_Heat_Recovery_HX=1.0
			Bypass_signal_Thermoelectric_HX=1.0
			Else
			Bypass_signal_Heat_Recovery_HX=0.0
			Bypass_signal_Thermoelectric_HX=0.0
			EndIf
			!fan control
		    Fan_Control_Signal= Schedule_Fans
	
	!***********************************************************************************************************************
	! ventilation mode, both active and passive HX are in operation to precisily control supply temperature
	! Ocupancy fan control	
	!***********************************************************************************************************************
	ElseIf ((Mode_Active_HX == 1) .and. (Mode_Fans == 0)) Then 
		Unit_OnOff=1
	    Electric_Current_to_Thermoelectric=PID_Control_Signal*Rated_Unit_Electric_Current
	    !aHX control 
		If (((Setpoint_Supply_Air_Temperature+Deadband_for_Supply_air_temperature)-Sensor_Heat_Recovery_Outlet_Temperature)<=0) Then !aHX cooling
		
			Thermoelectric_Cooling_Heating=0.0
			PID_Setpoint=Setpoint_Supply_Air_Temperature+Deadband_for_Supply_air_temperature
			PID_Controlled_Variable=Sensor_Supply_Air_Temperature
			PID_OnOff=1
			PID_Min_Ctrl=0
			PID_Max_Ctrl=1
			PID_Threshold=0
			PID_Gain=-0.1*PID_Gain_tunning_ratio
			PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
		
		ElseIf ((Setpoint_Supply_Air_Temperature-Sensor_Heat_Recovery_Outlet_Temperature)>=0) Then !aHX heating
			
			Thermoelectric_Cooling_Heating=1.0
			PID_Setpoint=Setpoint_Supply_Air_Temperature
			PID_Controlled_Variable=Sensor_Supply_Air_Temperature
			PID_OnOff=1
			PID_Min_Ctrl=0
			PID_Max_Ctrl=1
			PID_Threshold=0
			PID_Gain=0.1*PID_Gain_tunning_ratio
			PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
		
		Else !aHX heating
		
			Thermoelectric_Cooling_Heating=1.0
			PID_Setpoint=Setpoint_Supply_Air_Temperature
			PID_Controlled_Variable=Sensor_Supply_Air_Temperature
			PID_OnOff=0
			PID_Min_Ctrl=0
			PID_Max_Ctrl=1
			PID_Threshold=0
			PID_Gain=0.1*PID_Gain_tunning_ratio
			PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
			
		Endif
	    
		
		!bypass control
		If ((Sensor_Fresh_Air_Temperature>Lower_Comfort_Boundery_Temperature) .and. (Sensor_Fresh_Air_Temperature<Upper_Comfort_Boundery_Temperature)) Then
	    Bypass_signal_Heat_Recovery_HX=1.0
	    Bypass_signal_Thermoelectric_HX=1.0
		Else
		Bypass_signal_Heat_Recovery_HX=0.0
	    Bypass_signal_Thermoelectric_HX=0.0
	    EndIf

		!fan control
	    Fan_Control_Signal= DMIN1(Schedule_Occupancy*25*1.2/Rated_Unit_Flowrate,1.0)
	
	
	!***********************************************************************************************************************
	! discomfort hours mitigation mode, both active and passive HX are in operation for cooling and heating purposes
	!***********************************************************************************************************************
	ElseIf	((Mode_Active_HX == 2) .and. (Mode_Fans == 0)) Then 
					Unit_OnOff=1
					Electric_Current_to_Thermoelectric=PID_Control_Signal*Rated_Unit_Electric_Current
					
					If ((Sensor_Return_Air_Temperature>Lower_Comfort_Boundery_Temperature) .and. (Sensor_Return_Air_Temperature<Upper_Comfort_Boundery_Temperature)) Then ! ventilation mode
					!aHX control 
					
						If (((Setpoint_Supply_Air_Temperature+Deadband_for_Supply_air_temperature)-Sensor_Heat_Recovery_Outlet_Temperature)<0) Then !aHX cooling
						
							Thermoelectric_Cooling_Heating=0.0
							PID_Setpoint=Setpoint_Supply_Air_Temperature+Deadband_for_Supply_air_temperature
							PID_Controlled_Variable=Sensor_Supply_Air_Temperature
							PID_OnOff=1
							PID_Min_Ctrl=0
							PID_Max_Ctrl=1
							PID_Threshold=0
							PID_Gain=-0.1*PID_Gain_tunning_ratio
							PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
						
						ElseIf ((Setpoint_Supply_Air_Temperature-Sensor_Heat_Recovery_Outlet_Temperature)>0) Then !aHX heating
							
							Thermoelectric_Cooling_Heating=1.0
							PID_Setpoint=Setpoint_Supply_Air_Temperature
							PID_Controlled_Variable=Sensor_Supply_Air_Temperature
							PID_OnOff=1
							PID_Min_Ctrl=0
							PID_Max_Ctrl=1
							PID_Threshold=0
							PID_Gain=0.1*PID_Gain_tunning_ratio
							PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
						
						Else !no aHX conditioning
						
							Thermoelectric_Cooling_Heating=1.0
							PID_Setpoint=Setpoint_Supply_Air_Temperature
							PID_Controlled_Variable=Sensor_Supply_Air_Temperature
							PID_OnOff=0
							PID_Min_Ctrl=0
							PID_Max_Ctrl=1
							PID_Threshold=0
							PID_Gain=0.1*PID_Gain_tunning_ratio
							PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
							
						Endif
						
						
						!bypass control
						If ((Sensor_Fresh_Air_Temperature>Lower_Comfort_Boundery_Temperature) .and. (Sensor_Fresh_Air_Temperature<Upper_Comfort_Boundery_Temperature)) Then
						Bypass_signal_Heat_Recovery_HX=1.0
						Bypass_signal_Thermoelectric_HX=1.0
						Else
						Bypass_signal_Heat_Recovery_HX=0.0
						Bypass_signal_Thermoelectric_HX=0.0
						EndIf

						!fan control
						Fan_Control_Signal= DMIN1(Schedule_Occupancy*25*1.2/Rated_Unit_Flowrate,1.0)
						!Fan_Control_Signal= DMIN1(Schedule_Occupancy*25*1.2/Rated_Unit_Flowrate,1.0)
					Else ! discomfort mitigation mode
						
						
						!aHX control
						If ((Upper_Comfort_Boundery_Temperature-Sensor_Return_Air_Temperature)<0) Then !aHX cooling
						
							Thermoelectric_Cooling_Heating=0.0
							PID_Setpoint=Upper_Comfort_Boundery_Temperature
							PID_Controlled_Variable=Sensor_Return_Air_Temperature
							PID_OnOff=1
							PID_Min_Ctrl=0
							PID_Max_Ctrl=1
							PID_Threshold=0
							PID_Gain=-0.1*PID_Gain_tunning_ratio
							PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
						
						ElseIf ((Lower_Comfort_Boundery_Temperature-Sensor_Return_Air_Temperature)>0) Then !aHX heating
							
							Thermoelectric_Cooling_Heating=1.0
							PID_Setpoint=Setpoint_Supply_Air_Temperature
							PID_Controlled_Variable=Sensor_Supply_Air_Temperature
							PID_OnOff=1
							PID_Min_Ctrl=0
							PID_Max_Ctrl=1
							PID_Threshold=0
							PID_Gain=0.1*PID_Gain_tunning_ratio
							PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
						
						Else !aHX heating
						
							Thermoelectric_Cooling_Heating=1.0
							PID_Setpoint=Setpoint_Supply_Air_Temperature
							PID_Controlled_Variable=Sensor_Supply_Air_Temperature
							PID_OnOff=0
							PID_Min_Ctrl=0
							PID_Max_Ctrl=1
							PID_Threshold=0
							PID_Gain=0.1*PID_Gain_tunning_ratio
							PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
							
						Endif
						!bypass control
						If ((Sensor_Fresh_Air_Temperature>Lower_Comfort_Boundery_Temperature) .and. (Sensor_Fresh_Air_Temperature<Upper_Comfort_Boundery_Temperature)) Then
						Bypass_signal_Heat_Recovery_HX=1.0
						Bypass_signal_Thermoelectric_HX=1.0
						Else
						Bypass_signal_Heat_Recovery_HX=0.0
						Bypass_signal_Thermoelectric_HX=0.0
						EndIf
						!fan control
						If (Schedule_Occupancy<=0) Then
						Fan_Control_Signal=1
						Else
						Fan_Control_Signal= DMIN1(Schedule_Occupancy*30*1.2/Rated_Unit_Flowrate,1.0)		
						EndIf
				EndIf		
			
	
	!***********************************************************************************************************************
	! overcooling hours mitigation mode, both active and passive HX are in operation for cooling purposes
	!***********************************************************************************************************************
	ElseIf	((Mode_Active_HX == 3) .and. (Mode_Fans == 0)) Then 
		
		Unit_OnOff=1
	Electric_Current_to_Thermoelectric=PID_Control_Signal*Rated_Unit_Electric_Current
	    
		If (Sensor_Return_Air_Temperature<Upper_Comfort_Boundery_Temperature) Then ! ventilation mode
		!aHX control 
		
			If (((Setpoint_Supply_Air_Temperature+Deadband_for_Supply_air_temperature)-Sensor_Heat_Recovery_Outlet_Temperature)<0) Then !aHX cooling
			
				Thermoelectric_Cooling_Heating=0.0
				PID_Setpoint=Setpoint_Supply_Air_Temperature+Deadband_for_Supply_air_temperature
				PID_Controlled_Variable=Sensor_Supply_Air_Temperature
				PID_OnOff=1
				PID_Min_Ctrl=0
				PID_Max_Ctrl=1
				PID_Threshold=0
				PID_Gain=-0.1*PID_Gain_tunning_ratio
				PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
			
			ElseIf ((Setpoint_Supply_Air_Temperature-Sensor_Heat_Recovery_Outlet_Temperature)>0) Then !aHX heating
				
				Thermoelectric_Cooling_Heating=1.0
				PID_Setpoint=Setpoint_Supply_Air_Temperature
				PID_Controlled_Variable=Sensor_Supply_Air_Temperature
				PID_OnOff=1
				PID_Min_Ctrl=0
				PID_Max_Ctrl=1
				PID_Threshold=0
				PID_Gain=0.1*PID_Gain_tunning_ratio
				PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
			
			Else !no aHX conditioning
			
				Thermoelectric_Cooling_Heating=1.0
				PID_Setpoint=Setpoint_Supply_Air_Temperature
				PID_Controlled_Variable=Sensor_Supply_Air_Temperature
				PID_OnOff=0
				PID_Min_Ctrl=0
				PID_Max_Ctrl=1
				PID_Threshold=0
				PID_Gain=0.1*PID_Gain_tunning_ratio
				PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
				
			Endif
			
			
			!bypass control
			If ((Sensor_Fresh_Air_Temperature>Lower_Comfort_Boundery_Temperature) .and. (Sensor_Fresh_Air_Temperature<Upper_Comfort_Boundery_Temperature)) Then
			Bypass_signal_Heat_Recovery_HX=1.0
			Bypass_signal_Thermoelectric_HX=1.0
			Else
			Bypass_signal_Heat_Recovery_HX=0.0
			Bypass_signal_Thermoelectric_HX=0.0
			EndIf

			!fan control
			Fan_Control_Signal= Schedule_Fans
			!Fan_Control_Signal= DMIN1(Schedule_Occupancy*25*1.2/Rated_Unit_Flowrate,1.0)
		Else ! discomfort mitigation mode
			
			
			!aHX control
			!aHX cooling			
				Thermoelectric_Cooling_Heating=0.0
				PID_Setpoint=Upper_Comfort_Boundery_Temperature
				PID_Controlled_Variable=Sensor_Return_Air_Temperature
				PID_OnOff=1
				PID_Min_Ctrl=0
				PID_Max_Ctrl=1
				PID_Threshold=0
				PID_Gain=-0.1*PID_Gain_tunning_ratio
				PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
			

			!bypass control
		    If ((Sensor_Fresh_Air_Temperature>Lower_Comfort_Boundery_Temperature) .and. (Sensor_Fresh_Air_Temperature<Upper_Comfort_Boundery_Temperature)) Then
			Bypass_signal_Heat_Recovery_HX=1.0
			Bypass_signal_Thermoelectric_HX=1.0
			Else
			Bypass_signal_Heat_Recovery_HX=0.0
			Bypass_signal_Thermoelectric_HX=0.0
			EndIf
			!fan control
			If (Schedule_Occupancy<=0) Then
			Fan_Control_Signal=1
			Else
			Fan_Control_Signal= DMIN1(Schedule_Occupancy*30*1.2/Rated_Unit_Flowrate,1.0)		
			EndIf
	EndIf	
	
	
	
	!***********************************************************************************************************************
	! underheating hours mitigation mode, both active and passive HX are in operation for heating purposes 
	!***********************************************************************************************************************
	ElseIf	((Mode_Active_HX == 4) .and. (Mode_Fans == 0)) Then 
		Unit_OnOff=1
	    Electric_Current_to_Thermoelectric=PID_Control_Signal*Rated_Unit_Electric_Current
	    
		If ((Sensor_Return_Air_Temperature>Lower_Comfort_Boundery_Temperature)) Then ! ventilation mode
		!aHX control 
		
			If (((Setpoint_Supply_Air_Temperature+Deadband_for_Supply_air_temperature)-Sensor_Heat_Recovery_Outlet_Temperature)<0) Then !aHX cooling
			
				Thermoelectric_Cooling_Heating=0.0
				PID_Setpoint=Setpoint_Supply_Air_Temperature+Deadband_for_Supply_air_temperature
				PID_Controlled_Variable=Sensor_Supply_Air_Temperature
				PID_OnOff=1
				PID_Min_Ctrl=0
				PID_Max_Ctrl=1
				PID_Threshold=0
				PID_Gain=-0.1*PID_Gain_tunning_ratio
				PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
			
			ElseIf ((Setpoint_Supply_Air_Temperature-Sensor_Heat_Recovery_Outlet_Temperature)>0) Then !aHX heating
				
				Thermoelectric_Cooling_Heating=1.0
				PID_Setpoint=Setpoint_Supply_Air_Temperature
				PID_Controlled_Variable=Sensor_Supply_Air_Temperature
				PID_OnOff=1
				PID_Min_Ctrl=0
				PID_Max_Ctrl=1
				PID_Threshold=0
				PID_Gain=0.1*PID_Gain_tunning_ratio
				PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
			
			Else !no aHX conditioning
			
				Thermoelectric_Cooling_Heating=1.0
				PID_Setpoint=Setpoint_Supply_Air_Temperature
				PID_Controlled_Variable=Sensor_Supply_Air_Temperature
				PID_OnOff=0
				PID_Min_Ctrl=0
				PID_Max_Ctrl=1
				PID_Threshold=0
				PID_Gain=0.1*PID_Gain_tunning_ratio
				PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
				
			Endif
			
			
			!bypass control
			If ((Sensor_Fresh_Air_Temperature>Lower_Comfort_Boundery_Temperature) .and. (Sensor_Fresh_Air_Temperature<Upper_Comfort_Boundery_Temperature)) Then
			Bypass_signal_Heat_Recovery_HX=1.0
			Bypass_signal_Thermoelectric_HX=1.0
			Else
			Bypass_signal_Heat_Recovery_HX=0.0
			Bypass_signal_Thermoelectric_HX=0.0
			EndIf

			!fan control
			Fan_Control_Signal= DMIN1(Schedule_Occupancy*25*1.2/Rated_Unit_Flowrate,1.0)
			!Fan_Control_Signal= DMIN1(Schedule_Occupancy*25*1.2/Rated_Unit_Flowrate,1.0)
		Else ! discomfort mitigation mode
			
			
			!aHX control
			!aHX heating
				
				Thermoelectric_Cooling_Heating=1.0
				PID_Setpoint=Setpoint_Supply_Air_Temperature
				PID_Controlled_Variable=Sensor_Supply_Air_Temperature
				PID_OnOff=1
				PID_Min_Ctrl=0
				PID_Max_Ctrl=1
				PID_Threshold=0
				PID_Gain=0.1*PID_Gain_tunning_ratio
				PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
			
			
			!bypass control
		    If ((Sensor_Fresh_Air_Temperature>Lower_Comfort_Boundery_Temperature) .and. (Sensor_Fresh_Air_Temperature<Upper_Comfort_Boundery_Temperature)) Then
			Bypass_signal_Heat_Recovery_HX=1.0
			Bypass_signal_Thermoelectric_HX=1.0
			Else
			Bypass_signal_Heat_Recovery_HX=0.0
			Bypass_signal_Thermoelectric_HX=0.0
			EndIf
			!fan control
			If (Schedule_Occupancy<=0) Then
			Fan_Control_Signal=1
			Else
			Fan_Control_Signal= DMIN1(Schedule_Occupancy*30*1.2/Rated_Unit_Flowrate,1.0)		
			EndIf
	EndIf	
	
	
	!***********************************************************************************************************************
	!***********************************************************************************************************************
	Else
			Unit_OnOff=1
	        Electric_Current_to_Thermoelectric=PID_Control_Signal*Rated_Unit_Electric_Current
			!aHX control -off
	        Thermoelectric_Cooling_Heating=1.0
			PID_Setpoint=Setpoint_Supply_Air_Temperature
			PID_Controlled_Variable=Sensor_Supply_Air_Temperature
			PID_OnOff=0
			PID_Min_Ctrl=0
			PID_Max_Ctrl=1
			PID_Threshold=0
			PID_Gain=0.1*PID_Gain_tunning_ratio
			PID_Integral_Time=1/60*PID_Integral_time_tunnig_ratio
			!bypass control
		    If ((Sensor_Fresh_Air_Temperature>Lower_Comfort_Boundery_Temperature) .and. (Sensor_Fresh_Air_Temperature<Upper_Comfort_Boundery_Temperature)) Then
			Bypass_signal_Heat_Recovery_HX=1.0
			Bypass_signal_Thermoelectric_HX=1.0
			Else
			Bypass_signal_Heat_Recovery_HX=0.0
			Bypass_signal_Thermoelectric_HX=0.0
			EndIf
			!fan control
		    Fan_Control_Signal= DMIN1(Schedule_Occupancy*25*1.2/Rated_Unit_Flowrate,1.0)			
	EndIf
	
EndIf
	!-----------------------------------------------------------------------------------------------------------------------
	!If Needed, Get the Previous Control States if Discrete Controllers are Being Used (#)
	!Sample Code: CONTROL_LAST=getPreviousControlState(1)
	!-----------------------------------------------------------------------------------------------------------------------

	!-----------------------------------------------------------------------------------------------------------------------
	!If Needed, Get the Values from the Global Storage Array for the Static Variables (#)
	!Sample Code: STATIC1=getStaticArrayValue(1)
	!-----------------------------------------------------------------------------------------------------------------------

	!-----------------------------------------------------------------------------------------------------------------------
	!If Needed, Get the Initial Values of the Dynamic Variables from the Global Storage Array (#)
	!Sample Code: T_INITIAL_1=getDynamicArrayValueLastTimestep(1)
	!-----------------------------------------------------------------------------------------------------------------------

	!-----------------------------------------------------------------------------------------------------------------------
	!Perform All of the Calculations Here to Set the Outputs from the Model Based on the Inputs

	!Sample Code: OUT1=IN1+PAR1

	!If the model requires the solution of numerical derivatives, set these derivatives and get the current solution
	!Sample Code: T1=getNumericalSolution(1)
	!Sample Code: T2=getNumericalSolution(2)
	!Sample Code: DTDT1=3.*T2+7.*T1-15.
	!Sample Code: DTDT2=-2.*T1+11.*T2+21.
	!Sample Code: Call SetNumericalDerivative(1,DTDT1)
	!Sample Code: Call SetNumericalDerivative(2,DTDT2)

!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
   !Set the Initial Values of the Outputs (#,Value)
		Call SetOutputValue(1, Unit_OnOff) ! Unit On/Off
		Call SetOutputValue(2, Electric_Current_to_Thermoelectric) ! Electric Current to Thermoelectric
		Call SetOutputValue(3, Thermoelectric_Cooling_Heating) ! Thermoelectric HX Mode - Cooling/Heating
		Call SetOutputValue(4, Bypass_signal_Heat_Recovery_HX) ! Bypass signal - Heat Recovery HX
		Call SetOutputValue(5, Bypass_signal_Thermoelectric_HX) ! Bypass signal - Thermoelectric HX
		Call SetOutputValue(6, Fan_Control_Signal) ! Fan Control Signal
		Call SetOutputValue(7, PID_Setpoint) ! PID-Setpoint
		Call SetOutputValue(8, PID_Controlled_Variable) ! PID-Controlled variable
		Call SetOutputValue(9, PID_OnOff) ! PID-ON/OFF
		Call SetOutputValue(10, PID_Min_Ctrl) ! PID-Minimum control signal
		Call SetOutputValue(11, PID_Max_Ctrl) ! PID-Maximum control signal
		Call SetOutputValue(12, PID_Threshold) ! PID-Threshold for non-zero output
		Call SetOutputValue(13, PID_Gain) ! PID-Gain constant
		Call SetOutputValue(14, PID_Integral_Time) ! PID-Integral time
		Call SetOutputValue(15, 0.d0) ! PID-Derivative time

!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!If Needed, Store the Desired Disceret Control Signal Values for this Iteration (#,State)
!Sample Code:  Call SetDesiredDiscreteControlState(1,1)
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!If Needed, Store the Final value of the Dynamic Variables in the Global Storage Array (#,Value)
!Sample Code:  Call SetDynamicArrayValueThisIteration(1,T_FINAL_1)
!-----------------------------------------------------------------------------------------------------------------------
 
      Return
      End
!-----------------------------------------------------------------------------------------------------------------------

